# -*- coding: utf-8 -*-
# This file can be automatically generated by blender_addon_m17n_tools.
# See: https://github.com/UuuNyaa/blender_addon_m17n_tools
# It can (should) also be put in a different, specific py file.

import bpy

def _(msgid: str) -> str:
  return msgid

def iface_(msgid: str) -> str:
  return bpy.app.translations.pgettext_iface(msgid)

def register():
  bpy.app.translations.register(__name__, translation_dict)

def unregister():
  bpy.app.translations.unregister(__name__)

# ##### BEGIN AUTOGENERATED I18N SECTION #####
# NOTE: You can safely move around this auto-generated block (with the begin/end markers!),
#       and edit the translations by hand.
#       Just carefully respect the format of the tuple!

translation_dict = {
  "ja_JP": {
    #: mmd_uuunyaa_tools/__init__.py:41
    ("*", "Utility tools for MMD model & scene editing by Uuu(/>ω<)/Nyaa!."): "MMDモデル＆シーン編集のためのユーティリティーツールです。by Uuu(/>ω<)/Nyaa!",
    #: mmd_uuunyaa_tools/__init__.py:42
    ("*", "View3D > Sidebar > MMD Tools Panel"): "3Dビュー > サイドバー > MMD Toolsパネル",
    #: mmd_uuunyaa_tools/asset_search/actions.py:73
    ("*", "Failed to download assets from SmutBase. The response format may have changed."): "SmutBaseからのアセットダウンロードに失敗しました。レスポンスフォーマットが変わっている可能性があります。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:100
    ("*", "Failed to download assets from BowlRoll. Incorrect download key."): "BowlRollからのアセットダウンロードに失敗しました。ダウンロードキーが正しくありません。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:116
    ("*", "Failed to download assets from Google Drive. Incorrect download key."): "Google Driveからのアセットダウンロードに失敗しました。ダウンロードキーが正しくありません。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:137
    ("*", "Failed to download assets from uploader.jp. The response format may have changed."): "uploader.jpからのアセットダウンロードに失敗しました。レスポンスフォーマットが変わっている可能性があります。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:405
    ("*", "The file path is too long. This can be alleviated to some extent by shortening the Asset Extract Root Folder in the Add-on Preferences."): "ファイルパスが長すぎます。アドオンプリファレンスのアセット展開ルートフォルダーを短くすることで軽減できます。",
    #: mmd_uuunyaa_tools/asset_search/assets.py:33
    ("*", "All"): "全て",
    #: mmd_uuunyaa_tools/asset_search/assets.py:34
    ("*", "Model (.pmx)"): "モデル (.pmx)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:35
    ("*", "Model (.blend)"): "モデル (.blend)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:36
    ("*", "Motion (.vmd)"): "モーション (.vmd)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:37
    ("*", "Pose (.vpd)"): "ポーズ (.vpd)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:38
    ("*", "Lighting"): "照明",
    #: mmd_uuunyaa_tools/asset_search/assets.py:39
    ("*", "Material"): "マテリアル",
    #: mmd_uuunyaa_tools/asset_search/assets.py:40
    ("*", "World (.blend)"): "ワールド (.blend)",
    #: mmd_uuunyaa_tools/asset_search/operators.py:13
    ("Operator", "Reload Asset JSONs"): "アセットJSONをリロード",
    #: mmd_uuunyaa_tools/asset_search/operators.py:23
    ("Operator", "Update Assets JSON"): "アセットJSONを更新",
    #: mmd_uuunyaa_tools/asset_search/operators.py:40
    ("Operator", "Update Debug Asset JSON"): "デバッグアセットJSONを更新",
    #: mmd_uuunyaa_tools/asset_search/operators.py:57
    ("Operator", "Delete Debug Asset JSON"): "デバッグアセットJSONを削除",
    #: mmd_uuunyaa_tools/asset_search/operators.py:72
    ("Operator", "Delete Asset Cached Files"): "アセットキャッシュファイルを削除",
    #: mmd_uuunyaa_tools/asset_search/panels.py:266
    ("*", "Type:"): "タイプ:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:267
    ("*", "ID:"): "ID:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:269
    ("*", "Name:"): "名前:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:270
    ("*", "Aliases:"): "別名:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:271 mmd_uuunyaa_tools/asset_search/panels.py:348
    ("*", "Tags:"): "タグ:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:272
    ("*", "Updated at:"): "更新時刻",
    #: mmd_uuunyaa_tools/asset_search/panels.py:273
    ("*", "Note:"): "メモ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:275
    ("*", "Source:"): "配信元:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:280
    ("Operator", "Download"): "ダウンロード",
    #: mmd_uuunyaa_tools/asset_search/panels.py:283
    ("*", "Downloading"): "ダウンロード中",
    #: mmd_uuunyaa_tools/asset_search/panels.py:283 mmd_uuunyaa_tools/asset_search/panels.py:287 mmd_uuunyaa_tools/converters/physics/cloth.py:177
    ("*", "Cache:"): "キャッシュ:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:284
    ("Operator", "Cancel"): "キャンセル",
    #: mmd_uuunyaa_tools/asset_search/panels.py:288 mmd_uuunyaa_tools/asset_search/panels.py:300
    ("*", "Path:"): "パス:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:295 mmd_uuunyaa_tools/asset_search/panels.py:301
    ("Operator", "Import"): "インポート",
    #: mmd_uuunyaa_tools/asset_search/panels.py:304 mmd_uuunyaa_tools/asset_search/panels.py:307
    ("Operator", "Retry"): "リトライ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:331
    ("*", "UuuNyaa Asset Search"): "UuuNyaaアセットサーチ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:343
    ("*", "Asset type"): "アセットタイプ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:344 mmd_uuunyaa_tools/asset_search/panels.py:485
    ("*", "Query"): "クエリ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:351
    ("*", "Cached"): "キャッシュ済",
    #: mmd_uuunyaa_tools/asset_search/panels.py:364
    ("*", "{search_result_count} of {search_result_hit_count} results"): "{search_result_count} 件 / {search_result_hit_count} 件中",
    #: mmd_uuunyaa_tools/asset_search/panels.py:410
    ("*", "Invalid search result, Please search again."): "無効な検索結果です。再検索してください。",
    #: mmd_uuunyaa_tools/asset_search/panels.py:417
    ("*", "Loading {loading_count} item{plural_form_suffix}..."): "{loading_count} 件をロード中...",
    #: mmd_uuunyaa_tools/asset_search/panels.py:437
    ("*", "UuuNyaa Assets Operator"): "UuuNyaaアセットオペレーター",
    #: mmd_uuunyaa_tools/asset_search/panels.py:448
    ("*", "Reload local asset JSON files"): "ローカルアセットJSONファイルをリロード",
    #: mmd_uuunyaa_tools/asset_search/panels.py:454
    ("*", "Download and Update to the latest assets"): "最新アセットをダウンロードして更新",
    #: mmd_uuunyaa_tools/asset_search/panels.py:468
    ("*", "Debug"): "デバッグ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:474
    ("*", "Fetch an asset for debug"): "デバッグ用にアセットを取得",
    #: mmd_uuunyaa_tools/asset_search/panels.py:475
    ("*", "issue #"): "issue番号",
    #: mmd_uuunyaa_tools/asset_search/panels.py:482
    ("*", "Download and Update to the latest filtered assets for debug"): "デバッグ用にフィルタ済み最新アセットをダウンロードして更新",
    #: mmd_uuunyaa_tools/asset_search/panels.py:484
    ("*", "Repository"): "リポジトリ",
    #: mmd_uuunyaa_tools/asset_search/panels.py:486
    ("*", "Write to"): "書込み先",
    #: mmd_uuunyaa_tools/asset_search/panels.py:488
    ("Operator", "Update Assets JSON by query"): "アセットJSONをクエリで更新",
    #: mmd_uuunyaa_tools/checkers/operators.py:15
    ("Status", "Good"): "良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:16
    ("Status", "Average"): "普通",
    #: mmd_uuunyaa_tools/checkers/operators.py:17
    ("Status", "Warning"): "警告",
    #: mmd_uuunyaa_tools/checkers/operators.py:18
    ("Status", "Poor"): "劣る",
    #: mmd_uuunyaa_tools/checkers/operators.py:19
    ("Status", "Bad"): "悪い",
    #: mmd_uuunyaa_tools/checkers/operators.py:20
    ("Status", "Unknown"): "不明",
    #: mmd_uuunyaa_tools/checkers/operators.py:69
    ("Operator", "Check Eevee Rendering Performance"): "Eeveeレンダリングパフォーマンスチェック",
    #: mmd_uuunyaa_tools/checkers/operators.py:81
    ("*", "Blender Version"): "Blenderバージョン",
    #: mmd_uuunyaa_tools/checkers/operators.py:85
    ("*", ">= 2.93 LTS is Good"): ">= 2.93 LTSが良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:92
    ("*", "Render Engine"): "レンダーエンジン",
    #: mmd_uuunyaa_tools/checkers/operators.py:96
    ("*", "= Eevee is Good"): "= Eeveeが良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:114
    ("*", "Render Samples"): "レンダーのサンプル数",
    #: mmd_uuunyaa_tools/checkers/operators.py:118 mmd_uuunyaa_tools/checkers/operators.py:129 mmd_uuunyaa_tools/checkers/operators.py:182
    ("*", "<= 16 is Good"): "<= 16が良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:125
    ("*", "Viewport Samples"): "ビューポートのサンプル数",
    #: mmd_uuunyaa_tools/checkers/operators.py:136
    ("*", "Use Ambient Occlusion"): "アンビエントオクルージョン(AO)を使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:140 mmd_uuunyaa_tools/checkers/operators.py:150 mmd_uuunyaa_tools/checkers/operators.py:160 mmd_uuunyaa_tools/checkers/operators.py:214 mmd_uuunyaa_tools/checkers/operators.py:235 mmd_uuunyaa_tools/checkers/operators.py:248 mmd_uuunyaa_tools/checkers/operators.py:261 mmd_uuunyaa_tools/checkers/operators.py:274 mmd_uuunyaa_tools/checkers/operators.py:284 mmd_uuunyaa_tools/checkers/operators.py:294 mmd_uuunyaa_tools/checkers/operators.py:304 mmd_uuunyaa_tools/checkers/operators.py:314 mmd_uuunyaa_tools/checkers/operators.py:324 mmd_uuunyaa_tools/checkers/operators.py:334 mmd_uuunyaa_tools/checkers/operators.py:344 mmd_uuunyaa_tools/checkers/operators.py:354 mmd_uuunyaa_tools/checkers/operators.py:364 mmd_uuunyaa_tools/checkers/operators.py:377 mmd_uuunyaa_tools/checkers/operators.py:387 mmd_uuunyaa_tools/checkers/operators.py:397 mmd_uuunyaa_tools/checkers/operators.py:407
    ("*", "= False is Good"): "= Falseが良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:146 mmd_uuunyaa_tools/editors/operators.py:47
    ("*", "Use Bloom"): "ブルームを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:156 mmd_uuunyaa_tools/editors/operators.py:48
    ("*", "Use Motion Blur"): "モーションブラーを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:178
    ("*", "Depth of Field Max Size"): "被写界深度最大サイズ",
    #: mmd_uuunyaa_tools/checkers/operators.py:200
    ("*", "Subsurface Scattering Samples"): "サブサーフェススキャッタリングサンプル数",
    #: mmd_uuunyaa_tools/checkers/operators.py:204
    ("*", "<= 4 is Good"): "<= 4が良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:210
    ("*", "Use Screen Space Refraction"): "スクリーンスペース反射を使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:220
    ("*", "Use Half Res Trace"): "半解像度トレースを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:224
    ("*", "= True is Good"): "= Trueが良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:231
    ("*", "Use Compositing"): "コンポジティングを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:244
    ("*", "Pass Cryptomatte Object"): "Cryptomatteオブジェクトをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:257
    ("*", "Pass Cryptomatte Material"): "Cryptomatteマテリアルをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:270
    ("*", "Pass Cryptomatte Asset"): "Cryptomatteアセットをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:280
    ("*", "Pass Glossy Light"): "スペキュラーライトをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:290
    ("*", "Pass Diffuse Light"): "ディフューズライトをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:300
    ("*", "Pass Emit"): "放射をパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:310
    ("*", "Pass Glossy Color"): "スペキュラーカラーをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:320
    ("*", "Pass Diffuse Color"): "ディフューズカラーをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:330
    ("*", "Pass Shadow"): "影をパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:340
    ("*", "Pass Ambient Occlusion"): "アンビエントオクルージョン(AO)をパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:350
    ("*", "Pass Normal"): "ノーマルをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:360
    ("*", "Pass Bloom"): "ブルームをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:373
    ("*", "Pass Volume Light"): "ボリュームライトをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:383
    ("*", "Pass Z"): "Zをパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:393
    ("*", "Pass Environment"): "環境をパス",
    #: mmd_uuunyaa_tools/checkers/operators.py:403
    ("*", "Use Sequencer"): "シーケンサーを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:432
    ("*", "= JPEG is Good"): "= JPEGが良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:432
    ("*", "File Format"): "ファイルフォーマット",
    #: mmd_uuunyaa_tools/checkers/operators.py:468
    ("*", "Meshes Use Auto Smooth"): "メッシュが自動スムーズを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:472 mmd_uuunyaa_tools/checkers/operators.py:505
    ("*", "= 0 is Good"): "= 0が良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:501
    ("*", "Materials Use Alpha Hashed"): "マテリアルがアルファハッシュを使用",
    #: mmd_uuunyaa_tools/checkers/operators.py:511
    ("*", "Eevee Rendering Performance Checker"): "Eeveeレンダリングパフォーマンスチェッカー",
    #: mmd_uuunyaa_tools/checkers/operators.py:571
    ("*", "<= 0% is Good"): "<= 0%が良い",
    #: mmd_uuunyaa_tools/checkers/operators.py:571
    ("*", "Total Performance Impact"): "合計パフォーマンスインパクト",
    #: mmd_uuunyaa_tools/checkers/operators.py:599
    ("*", "Object with Impact Selection:"): "インパクトのあるオブジェクト選択:",
    #: mmd_uuunyaa_tools/checkers/operators.py:614
    ("Operator", "Select Mesh Objects with Use Auto Smooth"): "自動スムーズを使用するメッシュオブジェクトを選択",
    #: mmd_uuunyaa_tools/checkers/operators.py:637
    ("Operator", "Select Mesh Objects with Use Alpha Hashed"): "アルファハッシュを使用するメッシュオブジェクトを選択",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:19
    ("Operator", "Add Human (metarig) from MMD Armature"): "MMDアーマチュアからHuman (metarig)を追加",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:22
    ("Operator", "Clean Armature"): "アーマチュアを掃除",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:23
    ("Operator", "Clean Koikatsu Armature"): "コイカツアーマチュアを掃除",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:227
    ("Operator", "MMD compatibility focused Integrate"): "MMD互換性を重視して統合",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:230 mmd_uuunyaa_tools/converters/armatures/operators.py:282
    ("Operator", "Join Armatures"): "アーマチュアを結合",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:230 mmd_uuunyaa_tools/converters/armatures/operators.py:282
    ("*", "Join MMD and Rigify armatures"): "RigifyとMMDアーマチュアを結合",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:231 mmd_uuunyaa_tools/converters/armatures/operators.py:283
    ("*", "MMD main bone layer"): "MMDメインボーンレイヤー",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:232 mmd_uuunyaa_tools/converters/armatures/operators.py:284
    ("*", "MMD others bone layer"): "MMDその他ボーンレイヤー",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:233 mmd_uuunyaa_tools/converters/armatures/operators.py:285
    ("*", "MMD shadow bone layer"): "MMDシャドウボーンレイヤー",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:234 mmd_uuunyaa_tools/converters/armatures/operators.py:286
    ("*", "MMD dummy bone layer"): "MMDダミーボーンレイヤー",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:279
    ("Operator", "Rigify operability focused Integrate"): "Rigify操作性を重視して統合",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:331
    ("Operator", "Convert Rigify Armature to MMD compatible"): "RigifyアーマチュアをMMD互換に変換",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:335
    ("*", "Upper Body2 as"): "上半身２として",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:345
    ("*", "Lower Body as"): "下半身として",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:381 mmd_uuunyaa_tools/converters/armatures/operators.py:450 mmd_uuunyaa_tools/panels.py:60 mmd_uuunyaa_tools/panels.py:65
    ("Operator", "Apply MMD Rest Pose"): "MMDレストポーズを適用",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:384 mmd_uuunyaa_tools/converters/armatures/operators.py:453
    ("*", "Iterations"): "反復",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:384 mmd_uuunyaa_tools/converters/armatures/operators.py:453
    ("*", "Number of solving iterations"): "反復解決回数",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:385 mmd_uuunyaa_tools/converters/armatures/operators.py:454
    ("*", "Pose arms"): "腕をポーズ",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:386 mmd_uuunyaa_tools/converters/armatures/operators.py:455
    ("*", "Pose legs"): "脚をポーズ",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:387 mmd_uuunyaa_tools/converters/armatures/operators.py:456
    ("*", "Pose fingers"): "指をポーズ",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:422
    ("Operator", "Convert AutoRig Armature to MMD compatible"): "AutoRigアーマチュアをMMD互換に変換",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:14
    ("*", "UuuNyaa MMD Rigify"): "UuuNyaa MMD Rigify",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:50
    ("*", "MMD-Rigify:"): "MMD-Rigify",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:52 mmd_uuunyaa_tools/converters/armatures/panels.py:121
    ("*", "Integrated armature is not selected."): "統合アーマチュアが未選択です。",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:54
    ("*", "Bind"): "束縛",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:55 mmd_uuunyaa_tools/converters/armatures/panels.py:123
    ("*", "Eyes"): "目",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:57 mmd_uuunyaa_tools/converters/armatures/panels.py:68 mmd_uuunyaa_tools/converters/armatures/panels.py:125 mmd_uuunyaa_tools/converters/armatures/panels.py:133
    ("*", "Leg.L"): "脚.L",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:58 mmd_uuunyaa_tools/converters/armatures/panels.py:69 mmd_uuunyaa_tools/converters/armatures/panels.py:126 mmd_uuunyaa_tools/converters/armatures/panels.py:134
    ("*", "Leg.R"): "脚.R",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:60
    ("*", "Toe.L"): "つま先.L",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:61
    ("*", "Toe.R"): "つま先.R",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:63 mmd_uuunyaa_tools/converters/armatures/panels.py:128
    ("*", "IK-FK:"): "IK-FK",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:65 mmd_uuunyaa_tools/converters/armatures/panels.py:130
    ("*", "Arm.L"): "腕.L",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:66 mmd_uuunyaa_tools/converters/armatures/panels.py:131
    ("*", "Arm.R"): "腕.R",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:74
    ("*", "MMD Layers:"): "MMDレイヤー:",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:76 mmd_uuunyaa_tools/converters/armatures/panels.py:138
    ("*", "Main"): "メイン",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:79
    ("*", "Others"): "その他",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:82
    ("*", "Shadow"): "シャドウ",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:85
    ("*", "Dummy"): "ダミー",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:90
    ("*", "UuuNyaa MMD AutoRig"): "UuuNyaa MMD AutoRig",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:117
    ("*", "MMD-AutoRig:"): "MMD-AutoRig:",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:136
    ("*", "Layers:"): "レイヤー:",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:141
    ("*", "Sub"): "サブ",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:144
    ("*", "Spine"): "脊柱",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:147
    ("*", "Limbs"): "肢体",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:60 mmd_uuunyaa_tools/converters/physics/collision.py:25 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:65
    ("*", "Nothing"): "なし",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:73
    ("*", "Cotton"): "綿",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:96
    ("*", "Silk"): "絹",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:119
    ("*", "Breast Pyramid"): "胸ピラミッド",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:145
    ("*", "UuuNyaa Cloth Adjuster"): "UuuNyaaクロス調整器",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:167
    ("*", "Collision:"): "コリジョン:",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:173 mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:969 mmd_uuunyaa_tools/converters/physics/collision.py:78 mmd_uuunyaa_tools/converters/physics/rigid_body.py:29
    ("*", "Batch Operation:"): "一括操作:",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:174 mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:970 mmd_uuunyaa_tools/converters/physics/collision.py:79 mmd_uuunyaa_tools/converters/physics/rigid_body.py:30
    ("Operator", "Copy to Selected"): "選択にコピー",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:179 mmd_uuunyaa_tools/converters/physics/cloth.py:472 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:50
    ("*", "Simulation Start"): "シミュレーション開始",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:180 mmd_uuunyaa_tools/converters/physics/cloth.py:478 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:51
    ("*", "Simulation End"): "シミュレーション終了",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:186
    ("*", "Subdivision:"): "細分化:",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:187 mmd_uuunyaa_tools/converters/physics/cloth.py:327 mmd_uuunyaa_tools/converters/physics/cloth.py:508
    ("*", "Subdivision Levels"): "細分化レベル",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:192
    ("*", "Copy Cloth Adjuster Settings"): "クロス調整器をコピー",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:227
    ("Operator", "Select Cloth Mesh"): "クロスメッシュを選択",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:230 mmd_uuunyaa_tools/converters/physics/collision.py:120
    ("*", "Same MMD Model"): "同じMMDモデル",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:231 mmd_uuunyaa_tools/converters/physics/collision.py:121
    ("*", "Same Physics Settings"): "同じ物理設定",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:232
    ("*", "Same Cache Settings"): "同じキャッシュ設定",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:286
    ("Operator", "Remove Mesh Cloth"): "クロスを除去",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:323
    ("Operator", "Convert Rigid Body to Cloth"): "リジッドボディをクロスに変換",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:324
    ("*", "Select both the mesh to be deformed and the rigid body"): "変形対象メッシュとリジッドボディの両方を選択",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:328
    ("*", "Ribbon Stiffness"): "リボン剛性",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:330
    ("*", "Physics Mode"): "物理モード",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:335
    ("*", "Extend Ribbon Area"): "リボンエリア拡張",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:385
    ("*", "Multiple MMD models selected. Please select single model at a time."): "複数のMMDモデルが選択されています。ひとつずつモデルを選択してください。",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:415 mmd_uuunyaa_tools/converters/physics/collision.py:209 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:180
    ("*", "Presets"): "プリセット",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:422
    ("*", "Vertex Mass"): "頂点の質量",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:435
    ("*", "Stiffness"): "剛性",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:448 mmd_uuunyaa_tools/converters/physics/collision.py:216
    ("*", "Damping"): "減衰",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:454
    ("*", "Collision Quality"): "コリジョンの品質",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:460
    ("*", "Minimum Distance"): "最小距離",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:466
    ("*", "Impulse Clamping"): "撃力を制限",
    #: mmd_uuunyaa_tools/converters/physics/cloth_bone.py:15 mmd_uuunyaa_tools/converters/physics/panels.py:41
    ("*", "Stretch Bone to Vertex"): "ボーンを頂点にストレッチ",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:160
    ("*", "Target bones not found."): "対象ボーンが見つからない",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:775
    ("*", "Add Pyramid Mesh by Breast Bone"): "胸ボーンからピラミッドメッシュを追加",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:778
    ("*", "Head/Tail"): "ヘッド/テール",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:779
    ("*", "String Length Ratio"): "弦長比",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:780
    ("*", "Base Area Factor"): "底面積係数",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:781
    ("*", "Project Base Vertices Vertically"): "底面頂点を垂直に投影",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:822
    ("Operator", "Convert Pyramid Mesh to Cloth"): "ピラミッドメッシュをクロスに変換",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:825 mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:890
    ("*", "Boundary Expansion Hop Count"): "境界拡張ホップ数",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:887
    ("Operator", "Assign Pyramid Weights"): "ピラミッドへウェイトを割当",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:942
    ("*", "UuuNyaa Pyramid Cloth Adjuster"): "UuuNyaaピラミッドクロス調整器",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:959
    ("*", "Weights:"): "ウエイト:",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:965
    ("*", "Cloth Physics:"): "クロス物理:",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:975
    ("*", "Copy Pyramid Cloth Adjuster Settings"): "ピラミッドクロス調整器をコピー",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1004
    ("*", "String Pin Weight"): "弦固定ウェイト",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1010
    ("*", "Apex Pin Weight"): "頂点固定ウェイト",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1016
    ("*", "Base Pin Weight"): "底面固定ウェイト",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1022
    ("*", "Speed Multiplier"): "速度の乗数",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:38
    ("*", "Thin Smooth"): "薄くスムーズ",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:56
    ("*", "UuuNyaa Collision Adjuster"): "UuuNyaaコリジョン調整器",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:84
    ("Operator", "Copy Collision Adjuster Settings"): "コリジョン調整器をコピー",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:117
    ("Operator", "Select Collision Mesh"): "コリジョンメッシュを選択",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:168
    ("Operator", "Remove Mesh Collision"): "コリジョンを除去",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:222
    ("*", "Thickness Outer"): "外側の厚さ",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:228
    ("*", "Thickness Inner"): "内側の厚さ",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:234
    ("*", "Cloth Friction"): "摩擦",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:15
    ("*", "UuuNyaa Dynamic Paint Adjuster"): "UuuNyaaダイナミックペイント調整器",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:41
    ("*", "Cache"): "キャッシュ",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:78
    ("*", "Canvas Skin Press"): "キャンバス 肌圧迫",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:113
    ("*", "Brush Default"): "ブラシ デフォルト",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:187
    ("*", "Active Surface"): "アクティブサーフェス",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:22
    ("*", "UuuNyaa Physics"): "UuuNyaa物理演算",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:31
    ("*", "Relevant Selection:"): "関連選択",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:34
    ("*", "Collision Mesh"): "コリジョンメッシュ",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:39
    ("*", "Misc:"): "その他",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:46
    ("*", "MMD Model is not selected."): "MMDモデルが未選択",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:52
    ("*", "Rigid Body"): "リジッドボディ",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:61
    ("*", "Cloth Mesh"): "クロスメッシュ",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:67
    ("*", "Converter:"): "コンバーター:",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:71
    ("Operator", "Rigid Body to Cloth"): "リジッドボディをクロスに",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:76
    ("*", "Pyramid Cloth:"): "ピラミッドクロス:",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:78
    ("Operator", "Add Pyramid"): "ピラミッドを追加",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:79
    ("Operator", "Pyramid to Cloth"): "ピラミッドをクロスに",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:80
    ("Operator", "Repaint Weight"): "ウェイト再ペイント",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:15
    ("*", "UuuNyaa Rigid Body Adjuster"): "UuuNyaaリジッドボディ調整器",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:35
    ("Operator", "Select Rigid Body Mesh"): "リジッドボディメッシュを選択",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:38
    ("*", "Only in the MMD Model"): "MMDモデルのみ",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:39
    ("*", "Only the same Settings"): "同じ設定のみ",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:25
    ("*", "Auto"): "自動",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:26
    ("*", "Bone Constraint"): "ボーンコンストレイント",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:27
    ("*", "Surface Deform"): "サーフェス変形",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:76
    ("*", "No bones related with {rigid_body_name}, Please relate a bone to the Rigid Body."): "{rigid_body_name}に関連するボーンがありません。リジッドボディにボーンを関連付けてください。",
    #: mmd_uuunyaa_tools/editors/geometry_nodes.py:50
    ("*", "Point Random Rotation"): "ポイントランダム回転",
    #: mmd_uuunyaa_tools/editors/geometry_nodes.py:53
    ("*", "Random Rotation Point Instance"): "ランダム回転ポイントインスタンス",
    #: mmd_uuunyaa_tools/editors/menus.py:15 mmd_uuunyaa_tools/editors/menus.py:35 mmd_uuunyaa_tools/editors/menus.py:55
    ("*", "MMD UuuNyaa"): "MMD UuuNyaa",
    #: mmd_uuunyaa_tools/editors/menus.py:75
    ("*", "Select Moved"): "操作済選択",
    #: mmd_uuunyaa_tools/editors/menus.py:80
    ("Operator", "Moved"): "操作済",
    ("*", "Moved"): "操作済",
    #: mmd_uuunyaa_tools/editors/menus.py:85 mmd_uuunyaa_tools/editors/operators.py:314
    ("Operator", "Rotated"): "回転済",
    ("*", "Rotated"): "回転済",
    #: mmd_uuunyaa_tools/editors/menus.py:90 mmd_uuunyaa_tools/editors/operators.py:315
    ("Operator", "Translated"): "移動済",
    ("*", "Translated"): "移動済",
    #: mmd_uuunyaa_tools/editors/menus.py:95 mmd_uuunyaa_tools/editors/operators.py:316
    ("Operator", "Scaled"): "スケール済",
    ("*", "Scaled"): "スケール済",
    #: mmd_uuunyaa_tools/editors/nodes.py:223
    ("*", "Skin Color Adjust"): "肌カラー調整",
    #: mmd_uuunyaa_tools/editors/nodes.py:226 mmd_uuunyaa_tools/tuners/material_tuners.py:261
    ("*", "Skin Bump"): "肌 凹凸",
    #: mmd_uuunyaa_tools/editors/nodes.py:229
    ("*", "Fabric Woven Texture"): "布地織物テクスチャ",
    #: mmd_uuunyaa_tools/editors/nodes.py:232 mmd_uuunyaa_tools/tuners/material_tuners.py:389
    ("*", "Fabric Bump"): "布地 凹凸",
    #: mmd_uuunyaa_tools/editors/nodes.py:235
    ("*", "Wave Bump"): "波形バンプ",
    #: mmd_uuunyaa_tools/editors/nodes.py:238
    ("*", "Magic Bump"): "マジックバンプ",
    #: mmd_uuunyaa_tools/editors/nodes.py:241
    ("*", "Shadowless BSDF"): "影なしBSDF",
    #: mmd_uuunyaa_tools/editors/nodes.py:244
    ("*", "Gem BSDF"): "宝石BSDF",
    #: mmd_uuunyaa_tools/editors/nodes.py:247
    ("*", "Liquid BSDF"): "液体BSDF",
    #: mmd_uuunyaa_tools/editors/nodes.py:250
    ("*", "Knit Texture"): "編み物Bテクスチャ",
    #: mmd_uuunyaa_tools/editors/nodes.py:253
    ("*", "Leather Texture"): "革テクスチャ",
    #: mmd_uuunyaa_tools/editors/nodes.py:256
    ("*", "Watercolor Texture"): "水彩画テクスチャ",
    #: mmd_uuunyaa_tools/editors/nodes.py:259
    ("*", "MMDTexUV"): "MMDTexUV",
    #: mmd_uuunyaa_tools/editors/nodes.py:262 mmd_uuunyaa_tools/tuners/material_adjusters.py:103
    ("*", "Subsurface Adjuster"): "サブサーフェス調節器",
    #: mmd_uuunyaa_tools/editors/nodes.py:265 mmd_uuunyaa_tools/tuners/material_adjusters.py:58
    ("*", "Wet Adjuster"): "ウエット調節器",
    #: mmd_uuunyaa_tools/editors/nodes.py:268 mmd_uuunyaa_tools/tuners/material_adjusters.py:149
    ("*", "Emission Adjuster"): "エミッション調節器",
    #: mmd_uuunyaa_tools/editors/nodes.py:271 mmd_uuunyaa_tools/tuners/material_adjusters.py:194
    ("*", "Glitter Adjuster"): "グリッター調整器",
    #: mmd_uuunyaa_tools/editors/nodes.py:313
    ("*", "Sun Direction"): "太陽の方向",
    #: mmd_uuunyaa_tools/editors/operators.py:19
    ("Operator", "Convert Materials for Eevee"): "マテリアルをEevee用に変換",
    #: mmd_uuunyaa_tools/editors/operators.py:20
    ("*", "Convert materials of selected objects for Eevee."): "選択中オブジェクトマテリアルをEevee用に変換",
    #: mmd_uuunyaa_tools/editors/operators.py:43
    ("Operator", "Setup Render Engine for Eevee"): "レンダーエンジンをEevee用に設定",
    #: mmd_uuunyaa_tools/editors/operators.py:44
    ("*", "Setup render engine properties for Eevee."): "レンダーエンジンプロパティをEevee用に設定",
    #: mmd_uuunyaa_tools/editors/operators.py:49
    ("*", "Use Film Transparent"): "フィルム透過を使用",
    #: mmd_uuunyaa_tools/editors/operators.py:109
    ("Operator", "Show Message Box"): "メッセージボックスを表示",
    #: mmd_uuunyaa_tools/editors/operators.py:130
    ("Operator", "Remove Unused Vertex Groups"): "未使用頂点グループをすべて削除",
    #: mmd_uuunyaa_tools/editors/operators.py:131
    ("*", "Remove unused vertex groups from the active meshes"): "アクティブメッシュから未使用頂点グループをすべて削除",
    #: mmd_uuunyaa_tools/editors/operators.py:134
    ("*", "Weight Threshold"): "ウエイトしきい値",
    #: mmd_uuunyaa_tools/editors/operators.py:198
    ("Operator", "Select Shape Key Target Vertices"): "シェイプキー対象の頂点を選択",
    #: mmd_uuunyaa_tools/editors/operators.py:199
    ("*", "Select shape key target vertices from the active meshes"): "アクティブメッシュのシェイプキー対象の頂点を選択",
    #: mmd_uuunyaa_tools/editors/operators.py:202 mmd_uuunyaa_tools/editors/operators.py:249
    ("*", "Distance Threshold"): "距離しきい値",
    #: mmd_uuunyaa_tools/editors/operators.py:245
    ("Operator", "Remove Unused Shape Keys"): "未使用シェイプキーをすべて削除",
    #: mmd_uuunyaa_tools/editors/operators.py:246
    ("*", "Remove unused shape keys from the active meshes"): "アクティブメッシュから未使用シェイプキーをすべて削除",
    #: mmd_uuunyaa_tools/editors/operators.py:311
    ("Operator", "Select Moved Pose Bones"): "操作済ポーズボーンを選択",
    #: mmd_uuunyaa_tools/editors/operators.py:318
    ("*", "Tolerance"): "許容範囲",
    #: mmd_uuunyaa_tools/externals/addon_updater/addon_updater_ops.py:181
    ("*", "Update {} ready!"): "更新できます! {}",
    #: mmd_uuunyaa_tools/externals/addon_updater/addon_updater_ops.py:1067 mmd_uuunyaa_tools/externals/addon_updater/addon_updater_ops.py:1210
    ("*", "Update now to {}"): "今すぐ更新 {}",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:117
    ("*", "Add Skin Hair Mesh"): "体毛メッシュを追加",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:118
    ("*", "Construct a skin hair mesh"): "体毛メッシュを構築",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:134
    ("*", "Align"): "整列",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:136
    ("*", "Align the new object to the world"): "新規オブジェクトをワールド空間で整列",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:136
    ("*", "World"): "ワールド",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:137
    ("*", "Align the new object to the view"): "新規オブジェクトを視点で整列",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:137
    ("*", "View"): "ビュー",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:138
    ("*", "3D Cursor"): "3Dカーソル",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:138
    ("*", "Use the 3D cursor orientation for the new object"): "新規オブジェクトに3Dカーソルの回転を使用",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:145
    ("*", "Location"): "位置",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:149
    ("*", "Rotation"): "回転",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:180
    ("*", "UuuNyaa"): "UuuNyaa",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:184
    ("Operator", "Skin Hair"): "体毛",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:188
    ("*", "UuuNyaa Extras"): "UuuNyaaその他",
    #: mmd_uuunyaa_tools/panels.py:19
    ("*", "UuuNyaa Operator"): "UuuNyaaオペレーター",
    #: mmd_uuunyaa_tools/panels.py:29
    ("*", "Render:"): "レンダー:",
    #: mmd_uuunyaa_tools/panels.py:36
    ("*", "MMD to Rigify:"): "MMDからRigify:",
    #: mmd_uuunyaa_tools/panels.py:40
    ("Operator", "Add Metarig"): "メタリグを追加",
    #: mmd_uuunyaa_tools/panels.py:57
    ("*", "Rigify to MMD:"): "RigifyからMMD:",
    #: mmd_uuunyaa_tools/panels.py:59 mmd_uuunyaa_tools/panels.py:64
    ("Operator", "Convert to MMD compatible"): "MMD互換に変換",
    #: mmd_uuunyaa_tools/panels.py:62
    ("*", "(Experimental) Auto-Rig to MMD:"): "(実験的) Auto-RigからMMD:",
    #: mmd_uuunyaa_tools/preferences.py:22
    ("*", "Asset Search Results Max. Display Count"): "アセットサーチ結果の最大表示件数",
    #: mmd_uuunyaa_tools/preferences.py:23
    ("*", "Larger value is slower"): "大きい値ほど遅い",
    #: mmd_uuunyaa_tools/preferences.py:30
    ("*", "Asset JSONs Folder"): "アセットJSONフォルダー",
    #: mmd_uuunyaa_tools/preferences.py:31
    ("*", "Path to asset list JSON files"): "アセットJSONファイルのパス",
    #: mmd_uuunyaa_tools/preferences.py:37
    ("*", "Asset JSON Update Repository"): "アセットJSON更新リポジトリ",
    #: mmd_uuunyaa_tools/preferences.py:38
    ("*", "Specify the github repository which to retrieve the assets"): "アセットを取得するgithubリポジトリを指定",
    #: mmd_uuunyaa_tools/preferences.py:43
    ("*", "Asset JSON Update Query"): "アセットJSON更新クエリ",
    #: mmd_uuunyaa_tools/preferences.py:44
    ("*", "Specify the filter conditions for retrieving assets"): "アセットを取得するフィルタ条件を指定",
    #: mmd_uuunyaa_tools/preferences.py:49
    ("*", "Asset JSON Auto Update on Startup"): "起動時にアセットJSONを更新する",
    #: mmd_uuunyaa_tools/preferences.py:54
    ("*", "Asset Cache Folder"): "アセットキャッシュフォルダー",
    #: mmd_uuunyaa_tools/preferences.py:55
    ("*", "Path to asset cache folder"): "アセットキャッシュフォルダーのパス",
    #: mmd_uuunyaa_tools/preferences.py:61
    ("*", "Asset Max. Cache Size (MB)"): "アセット最大キャッシュサイズ(MB)",
    #: mmd_uuunyaa_tools/preferences.py:62
    ("*", "Maximum size (Mega bytes) of the asset cache folder"): "アセットキャッシュフォルダーの最大サイズ(メガバイト)",
    #: mmd_uuunyaa_tools/preferences.py:69
    ("*", "Asset Extract Root Folder"): "アセット展開ルートフォルダー",
    #: mmd_uuunyaa_tools/preferences.py:70
    ("*", "Path to extract the cached assets"): "キャッシュしたアセットの展開パス",
    #: mmd_uuunyaa_tools/preferences.py:76
    ("*", "Asset Extract Folder"): "アセット展開フォルダー",
    #: mmd_uuunyaa_tools/preferences.py:83
    ("*", "Asset Extract JSON"): "アセット展開JSON",
    #: mmd_uuunyaa_tools/preferences.py:129
    ("Operator", "Check now for mmd_uuunyaa_tools update"): "mmd_uuunyaa_toolsの更新を今すぐチェック",
    #: mmd_uuunyaa_tools/preferences.py:130
    ("*", "Auto-check for Update"): "更新を自動的にチェックする",
    #: mmd_uuunyaa_tools/preferences.py:131
    ("*", "Last check: Never"): "Last check: 未チェック",
    #: mmd_uuunyaa_tools/preferences.py:132
    ("Operator", "Addon is up to date"): "アドオンは最新です",
    #: mmd_uuunyaa_tools/preferences.py:133
    ("Operator", "Checking..."): "チェック中...",
    #: mmd_uuunyaa_tools/preferences.py:134
    ("*", "Choose 'Update Now' & press OK to install, "): "「今すぐ更新」を選択し、OKを押してインストール",
    #: mmd_uuunyaa_tools/preferences.py:135
    ("*", "or click outside window to defer"): "またはウィンドウの外をクリックして保留",
    #: mmd_uuunyaa_tools/preferences.py:136
    ("*", "No updates available"): "更新はありません",
    #: mmd_uuunyaa_tools/preferences.py:137
    ("*", "Press okay to dismiss dialog"): "OKを押してダイアログを閉じる",
    #: mmd_uuunyaa_tools/preferences.py:138
    ("*", "Check for update now?"): "今すぐ更新をチェックしますか?",
    #: mmd_uuunyaa_tools/preferences.py:139
    ("*", "Process update"): "更新処理",
    #: mmd_uuunyaa_tools/preferences.py:140
    ("*", "Decide to install, ignore, or defer new addon update"): "アドオンの更新、無視または保留を選択",
    #: mmd_uuunyaa_tools/preferences.py:141
    ("*", "Update Now"): "今すぐ更新",
    #: mmd_uuunyaa_tools/preferences.py:142
    ("*", "Install update now"): "今すぐ更新をインストール",
    #: mmd_uuunyaa_tools/preferences.py:143
    ("*", "Ignore"): "無視",
    #: mmd_uuunyaa_tools/preferences.py:144
    ("*", "Ignore this update to prevent future popups"): "このアップデートは無視して今後のポップアップを止める",
    #: mmd_uuunyaa_tools/preferences.py:145
    ("*", "Defer"): "保留",
    #: mmd_uuunyaa_tools/preferences.py:146
    ("*", "Defer choice till next blender session"): "次回のBlender起動まで保留",
    #: mmd_uuunyaa_tools/preferences.py:160
    ("*", "Browse Assets"): "アセットを閲覧",
    #: mmd_uuunyaa_tools/preferences.py:164
    ("*", "Query Examples"): "クエリ例",
    #: mmd_uuunyaa_tools/preferences.py:172
    ("*", "Asset Cache Usage:"): "アセットキャッシュ利用量",
    #: mmd_uuunyaa_tools/preferences.py:189
    ("*", "(Experimental) Add-on Update"): "(実験的) アドオン更新",
    #: mmd_uuunyaa_tools/preferences.py:194
    ("*", "Credits:"): "クレジット:",
    #: mmd_uuunyaa_tools/preferences.py:198
    ("*", "Rigid body Physics to Cloth Physics feature is the work of 小威廉伯爵."): "リジッドボディ物理からクロス物理機能は小威廉伯爵の作品です。",
    #: mmd_uuunyaa_tools/preferences.py:200
    ("*", "It was ported with his permission."): "この機能は本人の許可を得て移植したものです。",
    #: mmd_uuunyaa_tools/tuners/geometry_nodes_tuners.py:43 mmd_uuunyaa_tools/tuners/lighting_tuners.py:53 mmd_uuunyaa_tools/tuners/material_tuners.py:25
    ("*", "Reset"): "リセット",
    #: mmd_uuunyaa_tools/tuners/geometry_nodes_tuners.py:58
    ("*", "Sequins"): "スパンコール",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:66
    ("*", "Left Accent"): "左アクセント",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:80
    ("*", "Double Side Accent"): "両側アクセント",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:94
    ("*", "God Ray"): "ゴッドレイ",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:108
    ("*", "Backlight"): "バックライト",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:122
    ("*", "Light Probe Grid"): "イラディアンスボリューム",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:136
    ("*", "Shadowless"): "シャドウレス",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:61 mmd_uuunyaa_tools/tuners/material_adjusters.py:197
    ("*", "Specular"): "スペキュラー",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:62 mmd_uuunyaa_tools/tuners/material_adjusters.py:198 mmd_uuunyaa_tools/tuners/material_tuners.py:645
    ("*", "Roughness"): "粗さ",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:63 mmd_uuunyaa_tools/tuners/panels.py:182
    ("*", "Wet"): "ウェット",
    ("Operator", "Wet"): "ウェット",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:106 mmd_uuunyaa_tools/tuners/material_adjusters.py:152
    ("*", "Min"): "最小",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:107 mmd_uuunyaa_tools/tuners/material_adjusters.py:153
    ("*", "Max"): "最大",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:108 mmd_uuunyaa_tools/tuners/material_adjusters.py:154
    ("*", "Blood Color"): "血液カラー",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:109 mmd_uuunyaa_tools/tuners/material_adjusters.py:155 mmd_uuunyaa_tools/tuners/panels.py:181
    ("*", "Subsurface"): "サブサーフェス",
    ("Operator", "Subsurface"): "サブサーフェス",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:110 mmd_uuunyaa_tools/tuners/material_adjusters.py:156
    ("*", "Subsurface Color"): "サブサーフェスカラー",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:199 mmd_uuunyaa_tools/tuners/panels.py:183
    ("Operator", "Glitter"): "グリッター",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:48
    ("*", "Transparent"): "伝播",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:73
    ("*", "Eye Highlight"): "目ハイライト",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:98
    ("*", "Eye White"): "白目",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:123
    ("*", "Eye Iris"): "虹彩",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:153
    ("*", "Eye Lash"): "まつ毛",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:181
    ("*", "Hair Matte"): "髪 つや消し",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:209
    ("*", "Skin Mucosa"): "粘膜",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:303
    ("*", "Metal Noble"): "貴金属",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:331
    ("*", "Metal Base"): "卑金属",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:358
    ("*", "Stone Gem"): "石 宝石",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:420
    ("*", "Fabric Wave"): "布地 波形",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:453
    ("*", "Fabric Cotton"): "布地 綿",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:456 mmd_uuunyaa_tools/tuners/material_tuners.py:527 mmd_uuunyaa_tools/tuners/material_tuners.py:598 mmd_uuunyaa_tools/tuners/material_tuners.py:873
    ("*", "Color"): "カラー",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:457 mmd_uuunyaa_tools/tuners/material_tuners.py:528 mmd_uuunyaa_tools/tuners/material_tuners.py:599
    ("*", "Alpha"): "アルファ",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:458 mmd_uuunyaa_tools/tuners/material_tuners.py:529 mmd_uuunyaa_tools/tuners/material_tuners.py:601 mmd_uuunyaa_tools/tuners/material_tuners.py:650
    ("*", "Vector"): "ベクトル",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:459 mmd_uuunyaa_tools/tuners/material_tuners.py:530
    ("*", "Impurity"): "不純物",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:460 mmd_uuunyaa_tools/tuners/material_tuners.py:531 mmd_uuunyaa_tools/tuners/material_tuners.py:603 mmd_uuunyaa_tools/tuners/material_tuners.py:647 mmd_uuunyaa_tools/tuners/material_tuners.py:874
    ("*", "Scale"): "スケール",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:461 mmd_uuunyaa_tools/tuners/material_tuners.py:532
    ("*", "Angle"): "角度",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:462 mmd_uuunyaa_tools/tuners/material_tuners.py:533 mmd_uuunyaa_tools/tuners/material_tuners.py:648
    ("*", "Strength"): "強さ",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:463 mmd_uuunyaa_tools/tuners/material_tuners.py:534 mmd_uuunyaa_tools/tuners/material_tuners.py:600
    ("*", "Hole Alpha"): "穴アルファ",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:464 mmd_uuunyaa_tools/tuners/material_tuners.py:535
    ("*", "Gaps"): "すき間",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:465 mmd_uuunyaa_tools/tuners/material_tuners.py:536
    ("*", "Warp"): "縦糸",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:466 mmd_uuunyaa_tools/tuners/material_tuners.py:537
    ("*", "Woof"): "横糸",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:467 mmd_uuunyaa_tools/tuners/material_tuners.py:538
    ("*", "Distortion"): "歪み",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:468 mmd_uuunyaa_tools/tuners/material_tuners.py:539
    ("*", "Fibers"): "繊維",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:469 mmd_uuunyaa_tools/tuners/material_tuners.py:540
    ("*", "Fuzziness"): "曖昧さ",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:470 mmd_uuunyaa_tools/tuners/material_tuners.py:541
    ("*", "Errors"): "誤差",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:524
    ("*", "Fabric Silk"): "布地 絹",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:595
    ("*", "Fabric Knit"): "編物",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:602
    ("*", "Random Hue"): "ランダム色相",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:604
    ("*", "X Compression"): "X圧縮",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:640
    ("*", "Fabric Leather"): "革",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:643
    ("*", "Primary Color"): "プライマリーカラー",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:644
    ("*", "Secondary Color"): "セカンダリーカラー",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:646
    ("*", "Old/New"): "古い/新しい",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:649
    ("*", "Tartiary Detail"): "詳細さ",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:689
    ("*", "Plastic Gloss"): "プラスチック 光沢",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:717
    ("*", "Plastic Bump"): "プラスチック 凹凸",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:749
    ("*", "Plastic Matte"): "プラスチック つや消し",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:777
    ("*", "Plastic Emission"): "プラスチック 発光",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:806
    ("*", "Liquid Water"): "水",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:833
    ("*", "Liquid Cloudy"): "液体 白濁",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:870
    ("*", "Artistic Watercolor"): "表現手法 水彩画",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:875
    ("*", "Background Scale"): "背景スケール",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:876
    ("*", "Bleed Strength"): "滲み強度",
    #: mmd_uuunyaa_tools/tuners/operators.py:13
    ("Operator", "Tune Lighting"): "ライト調整",
    #: mmd_uuunyaa_tools/tuners/operators.py:31
    ("Operator", "Freeze Lighting"): "ライトを凍結",
    #: mmd_uuunyaa_tools/tuners/operators.py:48
    ("Operator", "Tune Material"): "マテリアル調整",
    #: mmd_uuunyaa_tools/tuners/operators.py:66
    ("Operator", "Attach Material Adjuster"): "マテリアル調整器を付加",
    #: mmd_uuunyaa_tools/tuners/operators.py:82
    ("Operator", "Detach Material Adjuster"): "マテリアル調整器を除去",
    #: mmd_uuunyaa_tools/tuners/operators.py:102
    ("Operator", "Tune Geometry Nodes"): "ジオメトリノードを調整",
    #: mmd_uuunyaa_tools/tuners/panels.py:20
    ("*", "MMD UuuNyaa Sky"): "MMD UuuNyaa Sky",
    #: mmd_uuunyaa_tools/tuners/panels.py:30
    ("*", "Light Strength"): "照明強度",
    #: mmd_uuunyaa_tools/tuners/panels.py:31
    ("*", "Image Strength"): "表示強度",
    #: mmd_uuunyaa_tools/tuners/panels.py:43
    ("*", "UuuNyaa World not found."): "UuuNyaaワールドが見つからない",
    #: mmd_uuunyaa_tools/tuners/panels.py:48
    ("*", "IrradianceVolume not found. Please add it."): "イラディアンスボリュームが見つからないので追加してください",
    #: mmd_uuunyaa_tools/tuners/panels.py:53
    ("*", "for Eevee lighting, check Render Properties."): "Eevee照明用 レンダープロパティを確認",
    #: mmd_uuunyaa_tools/tuners/panels.py:58
    ("*", "Bake Indirect Lighting"): "間接照明をベイク",
    #: mmd_uuunyaa_tools/tuners/panels.py:76
    ("*", "MMD UuuNyaa Lighting"): "MMD UuuNyaa照明",
    #: mmd_uuunyaa_tools/tuners/panels.py:115
    ("*", "MMD UuuNyaa Material"): "MMD UuuNyaaマテリアル",
    #: mmd_uuunyaa_tools/tuners/panels.py:151
    ("*", "MMD UuuNyaa Material Adjuster"): "MMD UuuNyaaマテリアル調整器",
    #: mmd_uuunyaa_tools/tuners/panels.py:168
    ("*", "{material_name} is unsupported. Select other material to be output from Principled BSDF."): "{material_name} は未未対応です。プリンシプルBSDFから出力のある他のマテリアルを選択してください。",
    #: mmd_uuunyaa_tools/tuners/panels.py:199
    ("*", "MMD UuuNyaa Geometry Nodes"): "MMD UuuNyaaジオメトリノード",
    #: mmd_uuunyaa_tools/tuners/properties.py:17
    ("*", "Choose the lighting you want to use"): "照明を選択",
    #: mmd_uuunyaa_tools/tuners/properties.py:38
    ("*", "Choose the material you want to use"): "マテリアルを選択",
    #: mmd_uuunyaa_tools/tuners/properties.py:63
    ("*", "Choose the geometry nodes you want to use"): "ジオメトリノードを選択",
  },
  "zh_CN": {
    #: mmd_uuunyaa_tools/__init__.py:41
    ("*", "Utility tools for MMD model & scene editing by Uuu(/>ω<)/Nyaa!."): "用于MMD模型和场景编辑的实用工具。by Uuu(/>ω<)/Nyaa!",
    #: mmd_uuunyaa_tools/__init__.py:42
    ("*", "View3D > Sidebar > MMD Tools Panel"): "3D视图 > 侧栏 > MMD Tools面板",
    #: mmd_uuunyaa_tools/asset_search/actions.py:73
    ("*", "Failed to download assets from SmutBase. The response format may have changed."): "从SmutBase下载资产失败。响应格式可能已经改变。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:100
    ("*", "Failed to download assets from BowlRoll. Incorrect download key."): "从BowlRoll下载资产失败。下载密钥不正确。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:116
    ("*", "Failed to download assets from Google Drive. Incorrect download key."): "从Google Drive下载资产失败。下载密钥不正确。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:137
    ("*", "Failed to download assets from uploader.jp. The response format may have changed."): "从uploader.jp下载资产失败。响应格式可能已经改变。",
    #: mmd_uuunyaa_tools/asset_search/actions.py:405
    ("*", "The file path is too long. This can be alleviated to some extent by shortening the Asset Extract Root Folder in the Add-on Preferences."): "文件路径太长。这可以通过缩短插件首选项中的资产提取根文件夹来在一定程度上缓解。",
    #: mmd_uuunyaa_tools/asset_search/assets.py:33
    ("*", "All"): "全部",
    #: mmd_uuunyaa_tools/asset_search/assets.py:34
    ("*", "Model (.pmx)"): "模型 (.pmx)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:35
    ("*", "Model (.blend)"): "模型 (.blend)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:36
    ("*", "Motion (.vmd)"): "运动 (.vmd)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:37
    ("*", "Pose (.vpd)"): "姿态 (.vpd)",
    #: mmd_uuunyaa_tools/asset_search/assets.py:38
    ("*", "Lighting"): "照明",
    #: mmd_uuunyaa_tools/asset_search/assets.py:39
    ("*", "Material"): "材质",
    #: mmd_uuunyaa_tools/asset_search/assets.py:40
    ("*", "World (.blend)"): "世界环境 (.blend)",
    #: mmd_uuunyaa_tools/asset_search/operators.py:13
    ("Operator", "Reload Asset JSONs"): "重新加载资产JSONs",
    #: mmd_uuunyaa_tools/asset_search/operators.py:23
    ("Operator", "Update Assets JSON"): "更新资产JSON",
    #: mmd_uuunyaa_tools/asset_search/operators.py:40
    ("Operator", "Update Debug Asset JSON"): "更新调试资产JSON",
    #: mmd_uuunyaa_tools/asset_search/operators.py:57
    ("Operator", "Delete Debug Asset JSON"): "删除调试资产JSON",
    #: mmd_uuunyaa_tools/asset_search/operators.py:72
    ("Operator", "Delete Asset Cached Files"): "删除资产缓存的文件",
    #: mmd_uuunyaa_tools/asset_search/panels.py:266
    ("*", "Type:"): "类型:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:267
    ("*", "ID:"): "ID:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:269
    ("*", "Name:"): "名称:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:270
    ("*", "Aliases:"): "别称:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:271 mmd_uuunyaa_tools/asset_search/panels.py:348
    ("*", "Tags:"): "标签:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:272
    ("*", "Updated at:"): "更新时刻:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:273
    ("*", "Note:"): "说明:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:275
    ("*", "Source:"): "来源:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:280
    ("Operator", "Download"): "下载",
    #: mmd_uuunyaa_tools/asset_search/panels.py:283
    ("*", "Downloading"): "现在下载",
    #: mmd_uuunyaa_tools/asset_search/panels.py:283 mmd_uuunyaa_tools/asset_search/panels.py:287 mmd_uuunyaa_tools/converters/physics/cloth.py:177
    ("*", "Cache:"): "缓存:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:284
    ("Operator", "Cancel"): "取消",
    #: mmd_uuunyaa_tools/asset_search/panels.py:288 mmd_uuunyaa_tools/asset_search/panels.py:300
    ("*", "Path:"): "路径:",
    #: mmd_uuunyaa_tools/asset_search/panels.py:295 mmd_uuunyaa_tools/asset_search/panels.py:301
    ("Operator", "Import"): "导入",
    #: mmd_uuunyaa_tools/asset_search/panels.py:304 mmd_uuunyaa_tools/asset_search/panels.py:307
    ("Operator", "Retry"): "重试",
    #: mmd_uuunyaa_tools/asset_search/panels.py:331
    ("*", "UuuNyaa Asset Search"): "UuuNyaa资产搜索",
    #: mmd_uuunyaa_tools/asset_search/panels.py:343
    ("*", "Asset type"): "资产类型",
    #: mmd_uuunyaa_tools/asset_search/panels.py:344 mmd_uuunyaa_tools/asset_search/panels.py:485
    ("*", "Query"): "查询",
    #: mmd_uuunyaa_tools/asset_search/panels.py:351
    ("*", "Cached"): "缓存了",
    #: mmd_uuunyaa_tools/asset_search/panels.py:364
    ("*", "{search_result_count} of {search_result_hit_count} results"): "{search_result_count} 项 / {search_result_hit_count} 项中",
    #: mmd_uuunyaa_tools/asset_search/panels.py:410
    ("*", "Invalid search result, Please search again."): "Invalid search result, Please search again.",
    #: mmd_uuunyaa_tools/asset_search/panels.py:417
    ("*", "Loading {loading_count} item{plural_form_suffix}..."): "正在加载{loading_count}个项目...",
    #: mmd_uuunyaa_tools/asset_search/panels.py:437
    ("*", "UuuNyaa Assets Operator"): "UuuNyaa资产操作项",
    #: mmd_uuunyaa_tools/asset_search/panels.py:448
    ("*", "Reload local asset JSON files"): "重新加载本地资产JSON文件",
    #: mmd_uuunyaa_tools/asset_search/panels.py:454
    ("*", "Download and Update to the latest assets"): "下载并更新到最新的资产",
    #: mmd_uuunyaa_tools/asset_search/panels.py:468
    ("*", "Debug"): "调试",
    #: mmd_uuunyaa_tools/asset_search/panels.py:474
    ("*", "Fetch an asset for debug"): "取出一个资产进行调试",
    #: mmd_uuunyaa_tools/asset_search/panels.py:475
    ("*", "issue #"): "issue编号",
    #: mmd_uuunyaa_tools/asset_search/panels.py:482
    ("*", "Download and Update to the latest filtered assets for debug"): "下载并更新到最新的过滤资产进行调试",
    #: mmd_uuunyaa_tools/asset_search/panels.py:484
    ("*", "Repository"): "仓库",
    #: mmd_uuunyaa_tools/asset_search/panels.py:486
    ("*", "Write to"): "写给",
    #: mmd_uuunyaa_tools/asset_search/panels.py:488
    ("Operator", "Update Assets JSON by query"): "通过查询更新资产JSON",
    #: mmd_uuunyaa_tools/checkers/operators.py:15
    ("Status", "Good"): "良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:16
    ("Status", "Average"): "平均",
    #: mmd_uuunyaa_tools/checkers/operators.py:17
    ("Status", "Warning"): "警告",
    #: mmd_uuunyaa_tools/checkers/operators.py:18
    ("Status", "Poor"): "不好",
    #: mmd_uuunyaa_tools/checkers/operators.py:19
    ("Status", "Bad"): "不良",
    #: mmd_uuunyaa_tools/checkers/operators.py:20
    ("Status", "Unknown"): "未知",
    #: mmd_uuunyaa_tools/checkers/operators.py:69
    ("Operator", "Check Eevee Rendering Performance"): "检查Eevee的渲染性能",
    #: mmd_uuunyaa_tools/checkers/operators.py:81
    ("*", "Blender Version"): "Blender版本",
    #: mmd_uuunyaa_tools/checkers/operators.py:85
    ("*", ">= 2.93 LTS is Good"): ">= 2.93 LTS是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:92
    ("*", "Render Engine"): "渲染引擎",
    #: mmd_uuunyaa_tools/checkers/operators.py:96
    ("*", "= Eevee is Good"): "= Eevee是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:114
    ("*", "Render Samples"): "渲染采样",
    #: mmd_uuunyaa_tools/checkers/operators.py:118 mmd_uuunyaa_tools/checkers/operators.py:129 mmd_uuunyaa_tools/checkers/operators.py:182
    ("*", "<= 16 is Good"): "<= 16是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:125
    ("*", "Viewport Samples"): "视图采样",
    #: mmd_uuunyaa_tools/checkers/operators.py:136
    ("*", "Use Ambient Occlusion"): "使用环境光遮蔽 (AO)",
    #: mmd_uuunyaa_tools/checkers/operators.py:140 mmd_uuunyaa_tools/checkers/operators.py:150 mmd_uuunyaa_tools/checkers/operators.py:160 mmd_uuunyaa_tools/checkers/operators.py:214 mmd_uuunyaa_tools/checkers/operators.py:235 mmd_uuunyaa_tools/checkers/operators.py:248 mmd_uuunyaa_tools/checkers/operators.py:261 mmd_uuunyaa_tools/checkers/operators.py:274 mmd_uuunyaa_tools/checkers/operators.py:284 mmd_uuunyaa_tools/checkers/operators.py:294 mmd_uuunyaa_tools/checkers/operators.py:304 mmd_uuunyaa_tools/checkers/operators.py:314 mmd_uuunyaa_tools/checkers/operators.py:324 mmd_uuunyaa_tools/checkers/operators.py:334 mmd_uuunyaa_tools/checkers/operators.py:344 mmd_uuunyaa_tools/checkers/operators.py:354 mmd_uuunyaa_tools/checkers/operators.py:364 mmd_uuunyaa_tools/checkers/operators.py:377 mmd_uuunyaa_tools/checkers/operators.py:387 mmd_uuunyaa_tools/checkers/operators.py:397 mmd_uuunyaa_tools/checkers/operators.py:407
    ("*", "= False is Good"): "= False是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:146 mmd_uuunyaa_tools/editors/operators.py:47
    ("*", "Use Bloom"): "使用辉光",
    #: mmd_uuunyaa_tools/checkers/operators.py:156 mmd_uuunyaa_tools/editors/operators.py:48
    ("*", "Use Motion Blur"): "使用运动模糊",
    #: mmd_uuunyaa_tools/checkers/operators.py:178
    ("*", "Depth of Field Max Size"): "景深最大尺寸",
    #: mmd_uuunyaa_tools/checkers/operators.py:200
    ("*", "Subsurface Scattering Samples"): "次表面散射采样",
    #: mmd_uuunyaa_tools/checkers/operators.py:204
    ("*", "<= 4 is Good"): "<= 4是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:210
    ("*", "Use Screen Space Refraction"): "使用屏幕空间折射",
    #: mmd_uuunyaa_tools/checkers/operators.py:220
    ("*", "Use Half Res Trace"): "使用半精度追踪",
    #: mmd_uuunyaa_tools/checkers/operators.py:224
    ("*", "= True is Good"): "= True是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:231
    ("*", "Use Compositing"): "使用合成处理",
    #: mmd_uuunyaa_tools/checkers/operators.py:244
    ("*", "Pass Cryptomatte Object"): "Cryptomatte物体通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:257
    ("*", "Pass Cryptomatte Material"): "Cryptomatte材质通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:270
    ("*", "Pass Cryptomatte Asset"): "Cryptomatte资源通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:280
    ("*", "Pass Glossy Light"): "高光灯光通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:290
    ("*", "Pass Diffuse Light"): "漫射灯光通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:300
    ("*", "Pass Emit"): "自发光(发射)通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:310
    ("*", "Pass Glossy Color"): "高光颜色通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:320
    ("*", "Pass Diffuse Color"): "漫射颜色通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:330
    ("*", "Pass Shadow"): "阴影通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:340
    ("*", "Pass Ambient Occlusion"): "环境光遮蔽 (AO)通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:350
    ("*", "Pass Normal"): "法向通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:360
    ("*", "Pass Bloom"): "辉光通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:373
    ("*", "Pass Volume Light"): "体积灯光通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:383
    ("*", "Pass Z"): "Z通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:393
    ("*", "Pass Environment"): "环境通道",
    #: mmd_uuunyaa_tools/checkers/operators.py:403
    ("*", "Use Sequencer"): "使用序列编辑器",
    #: mmd_uuunyaa_tools/checkers/operators.py:432
    ("*", "= JPEG is Good"): "= JPEG是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:432
    ("*", "File Format"): "文件格式",
    #: mmd_uuunyaa_tools/checkers/operators.py:468
    ("*", "Meshes Use Auto Smooth"): "网格使用自动平滑",
    #: mmd_uuunyaa_tools/checkers/operators.py:472 mmd_uuunyaa_tools/checkers/operators.py:505
    ("*", "= 0 is Good"): "= 0是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:501
    ("*", "Materials Use Alpha Hashed"): "纹理使用Alpha Hashed",
    #: mmd_uuunyaa_tools/checkers/operators.py:511
    ("*", "Eevee Rendering Performance Checker"): "Eevee的渲染性能检查器",
    #: mmd_uuunyaa_tools/checkers/operators.py:571
    ("*", "<= 0% is Good"): "<= 0%是良好",
    #: mmd_uuunyaa_tools/checkers/operators.py:571
    ("*", "Total Performance Impact"): "总的性能影响",
    #: mmd_uuunyaa_tools/checkers/operators.py:599
    ("*", "Object with Impact Selection:"): "有影响的物体选:",
    #: mmd_uuunyaa_tools/checkers/operators.py:614
    ("Operator", "Select Mesh Objects with Use Auto Smooth"): "选择使用自动平滑的网格物体",
    #: mmd_uuunyaa_tools/checkers/operators.py:637
    ("Operator", "Select Mesh Objects with Use Alpha Hashed"): "选择使用Alpha Hashed的网格物体",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:19
    ("Operator", "Add Human (metarig) from MMD Armature"): "从MMD骨架添加 Human (metarig)",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:22
    ("Operator", "Clean Armature"): "清洁骨架",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:23
    ("Operator", "Clean Koikatsu Armature"): "清洁Koikatsu骨架",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:227
    ("Operator", "MMD compatibility focused Integrate"): "注重MMD兼容性的整合",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:230 mmd_uuunyaa_tools/converters/armatures/operators.py:282
    ("Operator", "Join Armatures"): "合并骨架",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:230 mmd_uuunyaa_tools/converters/armatures/operators.py:282
    ("*", "Join MMD and Rigify armatures"): "合并Rigify和MMD骨架",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:231 mmd_uuunyaa_tools/converters/armatures/operators.py:283
    ("*", "MMD main bone layer"): "MMD主骨骼层",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:232 mmd_uuunyaa_tools/converters/armatures/operators.py:284
    ("*", "MMD others bone layer"): "MMD其他骨骼层",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:233 mmd_uuunyaa_tools/converters/armatures/operators.py:285
    ("*", "MMD shadow bone layer"): "MMD阴影骨骼层",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:234 mmd_uuunyaa_tools/converters/armatures/operators.py:286
    ("*", "MMD dummy bone layer"): "MMD伪骨骼层",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:279
    ("Operator", "Rigify operability focused Integrate"): "注重Rigify操作性的整合",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:331
    ("Operator", "Convert Rigify Armature to MMD compatible"): "将Rigify骨架转换为MMD兼容",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:335
    ("*", "Upper Body2 as"): "上半身2为",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:345
    ("*", "Lower Body as"): "下半身为",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:381 mmd_uuunyaa_tools/converters/armatures/operators.py:450 mmd_uuunyaa_tools/panels.py:60 mmd_uuunyaa_tools/panels.py:65
    ("Operator", "Apply MMD Rest Pose"): "应用MMD静置姿态",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:384 mmd_uuunyaa_tools/converters/armatures/operators.py:453
    ("*", "Iterations"): "迭代",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:384 mmd_uuunyaa_tools/converters/armatures/operators.py:453
    ("*", "Number of solving iterations"): "解算迭代的次数",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:385 mmd_uuunyaa_tools/converters/armatures/operators.py:454
    ("*", "Pose arms"): "姿势手臂",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:386 mmd_uuunyaa_tools/converters/armatures/operators.py:455
    ("*", "Pose legs"): "姿势腿",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:387 mmd_uuunyaa_tools/converters/armatures/operators.py:456
    ("*", "Pose fingers"): "姿势手指",
    #: mmd_uuunyaa_tools/converters/armatures/operators.py:422
    ("Operator", "Convert AutoRig Armature to MMD compatible"): "将AutoRig骨架转换为MMD兼容",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:14
    ("*", "UuuNyaa MMD Rigify"): "UuuNyaa MMD Rigify",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:50
    ("*", "MMD-Rigify:"): "MMD-Rigify",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:52 mmd_uuunyaa_tools/converters/armatures/panels.py:121
    ("*", "Integrated armature is not selected."): "未选择整合骨架",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:54
    ("*", "Bind"): "绑定",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:55 mmd_uuunyaa_tools/converters/armatures/panels.py:123
    ("*", "Eyes"): "两眼",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:57 mmd_uuunyaa_tools/converters/armatures/panels.py:68 mmd_uuunyaa_tools/converters/armatures/panels.py:125 mmd_uuunyaa_tools/converters/armatures/panels.py:133
    ("*", "Leg.L"): "腿.L",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:58 mmd_uuunyaa_tools/converters/armatures/panels.py:69 mmd_uuunyaa_tools/converters/armatures/panels.py:126 mmd_uuunyaa_tools/converters/armatures/panels.py:134
    ("*", "Leg.R"): "腿.R",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:60
    ("*", "Toe.L"): "脚趾.L",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:61
    ("*", "Toe.R"): "脚趾.R",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:63 mmd_uuunyaa_tools/converters/armatures/panels.py:128
    ("*", "IK-FK:"): "IK-FK",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:65 mmd_uuunyaa_tools/converters/armatures/panels.py:130
    ("*", "Arm.L"): "手臂.L",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:66 mmd_uuunyaa_tools/converters/armatures/panels.py:131
    ("*", "Arm.R"): "手臂.R",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:74
    ("*", "MMD Layers:"): "MMD层:",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:76 mmd_uuunyaa_tools/converters/armatures/panels.py:138
    ("*", "Main"): "主",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:79
    ("*", "Others"): "其他",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:82
    ("*", "Shadow"): "阴影",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:85
    ("*", "Dummy"): "伪",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:90
    ("*", "UuuNyaa MMD AutoRig"): "UuuNyaa MMD AutoRig",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:117
    ("*", "MMD-AutoRig:"): "MMD-AutoRig:",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:136
    ("*", "Layers:"): "层:",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:141
    ("*", "Sub"): "次级",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:144
    ("*", "Spine"): "脊柱",
    #: mmd_uuunyaa_tools/converters/armatures/panels.py:147
    ("*", "Limbs"): "肢体",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:60 mmd_uuunyaa_tools/converters/physics/collision.py:25 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:65
    ("*", "Nothing"): "无",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:73
    ("*", "Cotton"): "棉布",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:96
    ("*", "Silk"): "丝绸",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:119
    ("*", "Breast Pyramid"): "胸部金字塔",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:145
    ("*", "UuuNyaa Cloth Adjuster"): "UuuNyaa布料调整器",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:167
    ("*", "Collision:"): "碰撞:",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:173 mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:969 mmd_uuunyaa_tools/converters/physics/collision.py:78 mmd_uuunyaa_tools/converters/physics/rigid_body.py:29
    ("*", "Batch Operation:"): "批量操作:",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:174 mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:970 mmd_uuunyaa_tools/converters/physics/collision.py:79 mmd_uuunyaa_tools/converters/physics/rigid_body.py:30
    ("Operator", "Copy to Selected"): "复制到选定项",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:179 mmd_uuunyaa_tools/converters/physics/cloth.py:472 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:50
    ("*", "Simulation Start"): "模拟起始帧",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:180 mmd_uuunyaa_tools/converters/physics/cloth.py:478 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:51
    ("*", "Simulation End"): "模拟结束帧",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:186
    ("*", "Subdivision:"): "细分:",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:187 mmd_uuunyaa_tools/converters/physics/cloth.py:327 mmd_uuunyaa_tools/converters/physics/cloth.py:508
    ("*", "Subdivision Levels"): "细分级别",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:192
    ("*", "Copy Cloth Adjuster Settings"): "复制布料调整器设置",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:227
    ("Operator", "Select Cloth Mesh"): "选择布料网格",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:230 mmd_uuunyaa_tools/converters/physics/collision.py:120
    ("*", "Same MMD Model"): "相同的MMD模型",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:231 mmd_uuunyaa_tools/converters/physics/collision.py:121
    ("*", "Same Physics Settings"): "相同的物理设置",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:232
    ("*", "Same Cache Settings"): "相同的缓存设置",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:286
    ("Operator", "Remove Mesh Cloth"): "移除网格布料",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:323
    ("Operator", "Convert Rigid Body to Cloth"): "将刚体转换为布料",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:324
    ("*", "Select both the mesh to be deformed and the rigid body"): "选择要变形的网格和刚体",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:328
    ("*", "Ribbon Stiffness"): "丝带硬度",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:330
    ("*", "Physics Mode"): "物理模式",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:335
    ("*", "Extend Ribbon Area"): "扩展丝带区域",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:385
    ("*", "Multiple MMD models selected. Please select single model at a time."): "选择了多个MMD模型。请一次选择单一型号。",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:415 mmd_uuunyaa_tools/converters/physics/collision.py:209 mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:180
    ("*", "Presets"): "预设",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:422
    ("*", "Vertex Mass"): "顶点质量",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:435
    ("*", "Stiffness"): "硬度",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:448 mmd_uuunyaa_tools/converters/physics/collision.py:216
    ("*", "Damping"): "阻尼",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:454
    ("*", "Collision Quality"): "碰撞质量",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:460
    ("*", "Minimum Distance"): "最小距离",
    #: mmd_uuunyaa_tools/converters/physics/cloth.py:466
    ("*", "Impulse Clamping"): "冲量钳制",
    #: mmd_uuunyaa_tools/converters/physics/cloth_bone.py:15 mmd_uuunyaa_tools/converters/physics/panels.py:41
    ("*", "Stretch Bone to Vertex"): "拉伸骨骼到顶点",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:160
    ("*", "Target bones not found."): "没有找到目标骨骼",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:775
    ("*", "Add Pyramid Mesh by Breast Bone"): "从胸骨骼上添加金字塔网格",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:778
    ("*", "Head/Tail"): "头 / 尾",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:779
    ("*", "String Length Ratio"): "弦长比",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:780
    ("*", "Base Area Factor"): "基底面积系数",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:781
    ("*", "Project Base Vertices Vertically"): "垂直投影基底顶点",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:822
    ("Operator", "Convert Pyramid Mesh to Cloth"): "将金字塔网格转换为布料",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:825 mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:890
    ("*", "Boundary Expansion Hop Count"): "边界扩展跳数",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:887
    ("Operator", "Assign Pyramid Weights"): "分配金字塔权重",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:942
    ("*", "UuuNyaa Pyramid Cloth Adjuster"): "UuuNyaa金字塔布料调整器",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:959
    ("*", "Weights:"): "权重:",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:965
    ("*", "Cloth Physics:"): "布料物理:",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:975
    ("*", "Copy Pyramid Cloth Adjuster Settings"): "复制金字塔布料调整器设置",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1004
    ("*", "String Pin Weight"): "弦钉固权重",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1010
    ("*", "Apex Pin Weight"): "顶峰钉固权重",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1016
    ("*", "Base Pin Weight"): "基底钉固权重",
    #: mmd_uuunyaa_tools/converters/physics/cloth_pyramid.py:1022
    ("*", "Speed Multiplier"): "速率倍增",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:38
    ("*", "Thin Smooth"): "薄型平滑",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:56
    ("*", "UuuNyaa Collision Adjuster"): "UuuNyaa碰撞调整器",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:84
    ("Operator", "Copy Collision Adjuster Settings"): "复制碰撞调整器设置",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:117
    ("Operator", "Select Collision Mesh"): "选择碰撞网格",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:168
    ("Operator", "Remove Mesh Collision"): "移除碰撞网格",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:222
    ("*", "Thickness Outer"): "外部厚度",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:228
    ("*", "Thickness Inner"): "内部厚度",
    #: mmd_uuunyaa_tools/converters/physics/collision.py:234
    ("*", "Cloth Friction"): "摩擦",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:15
    ("*", "UuuNyaa Dynamic Paint Adjuster"): "UuuNyaa动态绘画调整器",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:41
    ("*", "Cache"): "缓存",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:78
    ("*", "Canvas Skin Press"): "画布 压迫皮肤",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:113
    ("*", "Brush Default"): "笔刷 默认",
    #: mmd_uuunyaa_tools/converters/physics/dynamic_paint.py:187
    ("*", "Active Surface"): "活动表面",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:22
    ("*", "UuuNyaa Physics"): "UuuNyaa物理计算",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:31
    ("*", "Relevant Selection:"): "相关选:",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:34
    ("*", "Collision Mesh"): "碰撞网格",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:39
    ("*", "Misc:"): "杂项",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:46
    ("*", "MMD Model is not selected."): "未选择MMD模型",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:52
    ("*", "Rigid Body"): "刚体",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:61
    ("*", "Cloth Mesh"): "布料网格",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:67
    ("*", "Converter:"): "转换器:",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:71
    ("Operator", "Rigid Body to Cloth"): "将刚体转换为布料",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:76
    ("*", "Pyramid Cloth:"): "金字塔布料:",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:78
    ("Operator", "Add Pyramid"): "添加金字塔",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:79
    ("Operator", "Pyramid to Cloth"): "将金字塔转换为布料",
    #: mmd_uuunyaa_tools/converters/physics/panels.py:80
    ("Operator", "Repaint Weight"): "重新权重绘制",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:15
    ("*", "UuuNyaa Rigid Body Adjuster"): "UuuNyaa刚体调整器",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:35
    ("Operator", "Select Rigid Body Mesh"): "刚体网格选",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:38
    ("*", "Only in the MMD Model"): "仅在MMD模型中",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body.py:39
    ("*", "Only the same Settings"): "只有相同的设置",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:25
    ("*", "Auto"): "自动",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:26
    ("*", "Bone Constraint"): "骨骼约束",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:27
    ("*", "Surface Deform"): "表面形变",
    #: mmd_uuunyaa_tools/converters/physics/rigid_body_to_cloth.py:76
    ("*", "No bones related with {rigid_body_name}, Please relate a bone to the Rigid Body."): "没有与{rigid_body_name}有关的骨骼，请将骨骼与刚体联系起来。",
    #: mmd_uuunyaa_tools/editors/geometry_nodes.py:50
    ("*", "Point Random Rotation"): "点随机旋转",
    #: mmd_uuunyaa_tools/editors/geometry_nodes.py:53
    ("*", "Random Rotation Point Instance"): "随机旋转点实例",
    #: mmd_uuunyaa_tools/editors/menus.py:15 mmd_uuunyaa_tools/editors/menus.py:35 mmd_uuunyaa_tools/editors/menus.py:55
    ("*", "MMD UuuNyaa"): "MMD UuuNyaa",
    #: mmd_uuunyaa_tools/editors/menus.py:75
    ("*", "Select Moved"): "选择移动过",
    #: mmd_uuunyaa_tools/editors/menus.py:80
    ("Operator", "Moved"): "移动过",
    ("*", "Moved"): "移动过",
    #: mmd_uuunyaa_tools/editors/menus.py:85 mmd_uuunyaa_tools/editors/operators.py:314
    ("Operator", "Rotated"): "旋转过",
    ("*", "Rotated"): "旋转过",
    #: mmd_uuunyaa_tools/editors/menus.py:90 mmd_uuunyaa_tools/editors/operators.py:315
    ("Operator", "Translated"): "平移过",
    ("*", "Translated"): "平移过",
    #: mmd_uuunyaa_tools/editors/menus.py:95 mmd_uuunyaa_tools/editors/operators.py:316
    ("Operator", "Scaled"): "缩放过",
    ("*", "Scaled"): "缩放过",
    #: mmd_uuunyaa_tools/editors/nodes.py:223
    ("*", "Skin Color Adjust"): "皮肤色调整",
    #: mmd_uuunyaa_tools/editors/nodes.py:226 mmd_uuunyaa_tools/tuners/material_tuners.py:261
    ("*", "Skin Bump"): "皮肤 凹凸",
    #: mmd_uuunyaa_tools/editors/nodes.py:229
    ("*", "Fabric Woven Texture"): "织物编织纹理",
    #: mmd_uuunyaa_tools/editors/nodes.py:232 mmd_uuunyaa_tools/tuners/material_tuners.py:389
    ("*", "Fabric Bump"): "织物 凹凸",
    #: mmd_uuunyaa_tools/editors/nodes.py:235
    ("*", "Wave Bump"): "波浪凹凸",
    #: mmd_uuunyaa_tools/editors/nodes.py:238
    ("*", "Magic Bump"): "迷幻凹凸",
    #: mmd_uuunyaa_tools/editors/nodes.py:241
    ("*", "Shadowless BSDF"): "无影BSDF",
    #: mmd_uuunyaa_tools/editors/nodes.py:244
    ("*", "Gem BSDF"): "宝石BSDF",
    #: mmd_uuunyaa_tools/editors/nodes.py:247
    ("*", "Liquid BSDF"): "液体BSDF",
    #: mmd_uuunyaa_tools/editors/nodes.py:250
    ("*", "Knit Texture"): "针织纹理",
    #: mmd_uuunyaa_tools/editors/nodes.py:253
    ("*", "Leather Texture"): "皮革纹理",
    #: mmd_uuunyaa_tools/editors/nodes.py:256
    ("*", "Watercolor Texture"): "水彩画纹理",
    #: mmd_uuunyaa_tools/editors/nodes.py:259
    ("*", "MMDTexUV"): "MMDTexUV",
    #: mmd_uuunyaa_tools/editors/nodes.py:262 mmd_uuunyaa_tools/tuners/material_adjusters.py:103
    ("*", "Subsurface Adjuster"): "次表面调整器",
    #: mmd_uuunyaa_tools/editors/nodes.py:265 mmd_uuunyaa_tools/tuners/material_adjusters.py:58
    ("*", "Wet Adjuster"): "湿润调整器",
    #: mmd_uuunyaa_tools/editors/nodes.py:268 mmd_uuunyaa_tools/tuners/material_adjusters.py:149
    ("*", "Emission Adjuster"): "发射调整器",
    #: mmd_uuunyaa_tools/editors/nodes.py:271 mmd_uuunyaa_tools/tuners/material_adjusters.py:194
    ("*", "Glitter Adjuster"): "闪耀调整器",
    #: mmd_uuunyaa_tools/editors/nodes.py:313
    ("*", "Sun Direction"): "太阳方向",
    #: mmd_uuunyaa_tools/editors/operators.py:19
    ("Operator", "Convert Materials for Eevee"): "转换材质给Eevee",
    #: mmd_uuunyaa_tools/editors/operators.py:20
    ("*", "Convert materials of selected objects for Eevee."): "为Eevee转换选物体的材质",
    #: mmd_uuunyaa_tools/editors/operators.py:43
    ("Operator", "Setup Render Engine for Eevee"): "为Eevee设置渲染引擎",
    #: mmd_uuunyaa_tools/editors/operators.py:44
    ("*", "Setup render engine properties for Eevee."): "为Eevee设置渲染引擎属性",
    #: mmd_uuunyaa_tools/editors/operators.py:49
    ("*", "Use Film Transparent"): "使用胶片透明",
    #: mmd_uuunyaa_tools/editors/operators.py:109
    ("Operator", "Show Message Box"): "显示信息框",
    #: mmd_uuunyaa_tools/editors/operators.py:130
    ("Operator", "Remove Unused Vertex Groups"): "删除未用到的顶点组",
    #: mmd_uuunyaa_tools/editors/operators.py:131
    ("*", "Remove unused vertex groups from the active meshes"): "从活动网格中删除未用到的顶点组",
    #: mmd_uuunyaa_tools/editors/operators.py:134
    ("*", "Weight Threshold"): "权重阈值",
    #: mmd_uuunyaa_tools/editors/operators.py:198
    ("Operator", "Select Shape Key Target Vertices"): "选择形态键目标顶点",
    #: mmd_uuunyaa_tools/editors/operators.py:199
    ("*", "Select shape key target vertices from the active meshes"): "从活动网格中删选择形态键目标顶点",
    #: mmd_uuunyaa_tools/editors/operators.py:202 mmd_uuunyaa_tools/editors/operators.py:249
    ("*", "Distance Threshold"): "距离阈值",
    #: mmd_uuunyaa_tools/editors/operators.py:245
    ("Operator", "Remove Unused Shape Keys"): "删除未用到的形态键",
    #: mmd_uuunyaa_tools/editors/operators.py:246
    ("*", "Remove unused shape keys from the active meshes"): "从活动网格中删除未用到的形态键",
    #: mmd_uuunyaa_tools/editors/operators.py:311
    ("Operator", "Select Moved Pose Bones"): "选择移动过的姿态骨骼",
    #: mmd_uuunyaa_tools/editors/operators.py:318
    ("*", "Tolerance"): "容差",
    #: mmd_uuunyaa_tools/externals/addon_updater/addon_updater_ops.py:181
    ("*", "Update {} ready!"): "可以更新!",
    #: mmd_uuunyaa_tools/externals/addon_updater/addon_updater_ops.py:1067 mmd_uuunyaa_tools/externals/addon_updater/addon_updater_ops.py:1210
    ("*", "Update now to {}"): "立即更新 {}",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:117
    ("*", "Add Skin Hair Mesh"): "添加体毛网格",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:118
    ("*", "Construct a skin hair mesh"): "创建一个体毛网格",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:134
    ("*", "Align"): "对齐",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:136
    ("*", "Align the new object to the world"): "将新建的物体与世界对齐",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:136
    ("*", "World"): "世界环境",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:137
    ("*", "Align the new object to the view"): "将新建的物体对齐到视图角度",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:137
    ("*", "View"): "视图",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:138
    ("*", "3D Cursor"): "3D游标",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:138
    ("*", "Use the 3D cursor orientation for the new object"): "对新物体使用3D游标方位",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:145
    ("*", "Location"): "位置",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:149
    ("*", "Rotation"): "旋转",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:180
    ("*", "UuuNyaa"): "UuuNyaa",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:184
    ("Operator", "Skin Hair"): "体毛",
    #: mmd_uuunyaa_tools/generators/skin_hair.py:188
    ("*", "UuuNyaa Extras"): "UuuNyaa其他项",
    #: mmd_uuunyaa_tools/panels.py:19
    ("*", "UuuNyaa Operator"): "UuuNyaa操作项",
    #: mmd_uuunyaa_tools/panels.py:29
    ("*", "Render:"): "渲染:",
    #: mmd_uuunyaa_tools/panels.py:36
    ("*", "MMD to Rigify:"): "MMD到Rigify:",
    #: mmd_uuunyaa_tools/panels.py:40
    ("Operator", "Add Metarig"): "添加Metarig",
    #: mmd_uuunyaa_tools/panels.py:57
    ("*", "Rigify to MMD:"): "Rigify到MMD:",
    #: mmd_uuunyaa_tools/panels.py:59 mmd_uuunyaa_tools/panels.py:64
    ("Operator", "Convert to MMD compatible"): "转换为MMD兼容",
    #: mmd_uuunyaa_tools/panels.py:62
    ("*", "(Experimental) Auto-Rig to MMD:"): "(实验的) Auto-Rig到MMD:",
    #: mmd_uuunyaa_tools/preferences.py:22
    ("*", "Asset Search Results Max. Display Count"): "显示的资产搜索结果的最大数量",
    #: mmd_uuunyaa_tools/preferences.py:23
    ("*", "Larger value is slower"): "数值越大越慢",
    #: mmd_uuunyaa_tools/preferences.py:30
    ("*", "Asset JSONs Folder"): "资产JSONs文件夹",
    #: mmd_uuunyaa_tools/preferences.py:31
    ("*", "Path to asset list JSON files"): "资产清单JSON文件的路径",
    #: mmd_uuunyaa_tools/preferences.py:37
    ("*", "Asset JSON Update Repository"): "资产JSON更新仓库",
    #: mmd_uuunyaa_tools/preferences.py:38
    ("*", "Specify the github repository which to retrieve the assets"): "指定要检索资产的github仓库",
    #: mmd_uuunyaa_tools/preferences.py:43
    ("*", "Asset JSON Update Query"): "资产JSON更新查询",
    #: mmd_uuunyaa_tools/preferences.py:44
    ("*", "Specify the filter conditions for retrieving assets"): "指定检索资产的过滤条件",
    #: mmd_uuunyaa_tools/preferences.py:49
    ("*", "Asset JSON Auto Update on Startup"): "资产JSON在启动时自动更新",
    #: mmd_uuunyaa_tools/preferences.py:54
    ("*", "Asset Cache Folder"): "资产缓存的文件夹",
    #: mmd_uuunyaa_tools/preferences.py:55
    ("*", "Path to asset cache folder"): "资产缓存的文件夹的路径",
    #: mmd_uuunyaa_tools/preferences.py:61
    ("*", "Asset Max. Cache Size (MB)"): "最大的资产缓存大小(MB)",
    #: mmd_uuunyaa_tools/preferences.py:62
    ("*", "Maximum size (Mega bytes) of the asset cache folder"): "资产缓存文件夹的最大尺寸(兆字节)",
    #: mmd_uuunyaa_tools/preferences.py:69
    ("*", "Asset Extract Root Folder"): "资产提取根文件夹",
    #: mmd_uuunyaa_tools/preferences.py:70
    ("*", "Path to extract the cached assets"): "提取缓存资产的路径",
    #: mmd_uuunyaa_tools/preferences.py:76
    ("*", "Asset Extract Folder"): "资产提取文件夹",
    #: mmd_uuunyaa_tools/preferences.py:83
    ("*", "Asset Extract JSON"): "资产提取JSON",
    #: mmd_uuunyaa_tools/preferences.py:129
    ("Operator", "Check now for mmd_uuunyaa_tools update"): "立即检查mmd_uuunyaa_tools的更新",
    #: mmd_uuunyaa_tools/preferences.py:130
    ("*", "Auto-check for Update"): "自动检查更新",
    #: mmd_uuunyaa_tools/preferences.py:131
    ("*", "Last check: Never"): "Last check: 未检查",
    #: mmd_uuunyaa_tools/preferences.py:132
    ("Operator", "Addon is up to date"): "插件是最新的",
    #: mmd_uuunyaa_tools/preferences.py:133
    ("Operator", "Checking..."): "检查...",
    #: mmd_uuunyaa_tools/preferences.py:134
    ("*", "Choose 'Update Now' & press OK to install, "): "选择「立即更新」&确定进行安装。",
    #: mmd_uuunyaa_tools/preferences.py:135
    ("*", "or click outside window to defer"): "或在窗口外点击推迟",
    #: mmd_uuunyaa_tools/preferences.py:136
    ("*", "No updates available"): "没有更新",
    #: mmd_uuunyaa_tools/preferences.py:137
    ("*", "Press okay to dismiss dialog"): "按确定关闭对话框",
    #: mmd_uuunyaa_tools/preferences.py:138
    ("*", "Check for update now?"): "立即检查更新？",
    #: mmd_uuunyaa_tools/preferences.py:139
    ("*", "Process update"): "更新过程",
    #: mmd_uuunyaa_tools/preferences.py:140
    ("*", "Decide to install, ignore, or defer new addon update"): "选择更新、忽略或推迟该插件",
    #: mmd_uuunyaa_tools/preferences.py:141
    ("*", "Update Now"): "立即更新",
    #: mmd_uuunyaa_tools/preferences.py:142
    ("*", "Install update now"): "立即安装更新",
    #: mmd_uuunyaa_tools/preferences.py:143
    ("*", "Ignore"): "忽略",
    #: mmd_uuunyaa_tools/preferences.py:144
    ("*", "Ignore this update to prevent future popups"): "忽略此更新，以防止今后的弹出窗口",
    #: mmd_uuunyaa_tools/preferences.py:145
    ("*", "Defer"): "推迟",
    #: mmd_uuunyaa_tools/preferences.py:146
    ("*", "Defer choice till next blender session"): "推迟到下次启动时再做选择",
    #: mmd_uuunyaa_tools/preferences.py:160
    ("*", "Browse Assets"): "浏览资产",
    #: mmd_uuunyaa_tools/preferences.py:164
    ("*", "Query Examples"): "查询实例",
    #: mmd_uuunyaa_tools/preferences.py:172
    ("*", "Asset Cache Usage:"): "资产缓存使用情况",
    #: mmd_uuunyaa_tools/preferences.py:189
    ("*", "(Experimental) Add-on Update"): "(实验的) 插件更新",
    #: mmd_uuunyaa_tools/preferences.py:194
    ("*", "Credits:"): "版权:",
    #: mmd_uuunyaa_tools/preferences.py:198
    ("*", "Rigid body Physics to Cloth Physics feature is the work of 小威廉伯爵."): "刚体物理到布料物理的功能是小威廉伯爵的工作。",
    #: mmd_uuunyaa_tools/preferences.py:200
    ("*", "It was ported with his permission."): "这是经他许可的移植。",
    #: mmd_uuunyaa_tools/tuners/geometry_nodes_tuners.py:43 mmd_uuunyaa_tools/tuners/lighting_tuners.py:53 mmd_uuunyaa_tools/tuners/material_tuners.py:25
    ("*", "Reset"): "重置",
    #: mmd_uuunyaa_tools/tuners/geometry_nodes_tuners.py:58
    ("*", "Sequins"): "亮片",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:66
    ("*", "Left Accent"): "左侧重点",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:80
    ("*", "Double Side Accent"): "双侧重点",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:94
    ("*", "God Ray"): "上帝之光",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:108
    ("*", "Backlight"): "背光",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:122
    ("*", "Light Probe Grid"): "辐射体积",
    #: mmd_uuunyaa_tools/tuners/lighting_tuners.py:136
    ("*", "Shadowless"): "无影",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:61 mmd_uuunyaa_tools/tuners/material_adjusters.py:197
    ("*", "Specular"): "高光",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:62 mmd_uuunyaa_tools/tuners/material_adjusters.py:198 mmd_uuunyaa_tools/tuners/material_tuners.py:645
    ("*", "Roughness"): "糙度",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:63 mmd_uuunyaa_tools/tuners/panels.py:182
    ("*", "Wet"): "湿润",
    ("Operator", "Wet"): "湿润",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:106 mmd_uuunyaa_tools/tuners/material_adjusters.py:152
    ("*", "Min"): "最小",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:107 mmd_uuunyaa_tools/tuners/material_adjusters.py:153
    ("*", "Max"): "最大",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:108 mmd_uuunyaa_tools/tuners/material_adjusters.py:154
    ("*", "Blood Color"): "血液颜色",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:109 mmd_uuunyaa_tools/tuners/material_adjusters.py:155 mmd_uuunyaa_tools/tuners/panels.py:181
    ("*", "Subsurface"): "次表面",
    ("Operator", "Subsurface"): "次表面",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:110 mmd_uuunyaa_tools/tuners/material_adjusters.py:156
    ("*", "Subsurface Color"): "次表面颜色",
    #: mmd_uuunyaa_tools/tuners/material_adjusters.py:199 mmd_uuunyaa_tools/tuners/panels.py:183
    ("Operator", "Glitter"): "闪耀",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:48
    ("*", "Transparent"): "透明",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:73
    ("*", "Eye Highlight"): "眼高亮",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:98
    ("*", "Eye White"): "眼白",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:123
    ("*", "Eye Iris"): "眼睛虹膜",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:153
    ("*", "Eye Lash"): "眼睫毛",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:181
    ("*", "Hair Matte"): "头发 哑光",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:209
    ("*", "Skin Mucosa"): "粘膜",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:303
    ("*", "Metal Noble"): "贵重金属",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:331
    ("*", "Metal Base"): "基本金属",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:358
    ("*", "Stone Gem"): "石头 宝石",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:420
    ("*", "Fabric Wave"): "织物 波浪",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:453
    ("*", "Fabric Cotton"): "织物 棉布",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:456 mmd_uuunyaa_tools/tuners/material_tuners.py:527 mmd_uuunyaa_tools/tuners/material_tuners.py:598 mmd_uuunyaa_tools/tuners/material_tuners.py:873
    ("*", "Color"): "颜色",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:457 mmd_uuunyaa_tools/tuners/material_tuners.py:528 mmd_uuunyaa_tools/tuners/material_tuners.py:599
    ("*", "Alpha"): "Alpha",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:458 mmd_uuunyaa_tools/tuners/material_tuners.py:529 mmd_uuunyaa_tools/tuners/material_tuners.py:601 mmd_uuunyaa_tools/tuners/material_tuners.py:650
    ("*", "Vector"): "矢量",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:459 mmd_uuunyaa_tools/tuners/material_tuners.py:530
    ("*", "Impurity"): "杂质",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:460 mmd_uuunyaa_tools/tuners/material_tuners.py:531 mmd_uuunyaa_tools/tuners/material_tuners.py:603 mmd_uuunyaa_tools/tuners/material_tuners.py:647 mmd_uuunyaa_tools/tuners/material_tuners.py:874
    ("*", "Scale"): "缩放",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:461 mmd_uuunyaa_tools/tuners/material_tuners.py:532
    ("*", "Angle"): "角度",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:462 mmd_uuunyaa_tools/tuners/material_tuners.py:533 mmd_uuunyaa_tools/tuners/material_tuners.py:648
    ("*", "Strength"): "强度/力度",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:463 mmd_uuunyaa_tools/tuners/material_tuners.py:534 mmd_uuunyaa_tools/tuners/material_tuners.py:600
    ("*", "Hole Alpha"): "孔Alpha",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:464 mmd_uuunyaa_tools/tuners/material_tuners.py:535
    ("*", "Gaps"): "差距",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:465 mmd_uuunyaa_tools/tuners/material_tuners.py:536
    ("*", "Warp"): "经线",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:466 mmd_uuunyaa_tools/tuners/material_tuners.py:537
    ("*", "Woof"): "纬线",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:467 mmd_uuunyaa_tools/tuners/material_tuners.py:538
    ("*", "Distortion"): "畸变",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:468 mmd_uuunyaa_tools/tuners/material_tuners.py:539
    ("*", "Fibers"): "纤维",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:469 mmd_uuunyaa_tools/tuners/material_tuners.py:540
    ("*", "Fuzziness"): "模糊性",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:470 mmd_uuunyaa_tools/tuners/material_tuners.py:541
    ("*", "Errors"): "錯誤",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:524
    ("*", "Fabric Silk"): "织物 丝绸",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:595
    ("*", "Fabric Knit"): "织物 针织",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:602
    ("*", "Random Hue"): "随机色相",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:604
    ("*", "X Compression"): "X压缩",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:640
    ("*", "Fabric Leather"): "织物 皮革",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:643
    ("*", "Primary Color"): "主色",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:644
    ("*", "Secondary Color"): "二次色",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:646
    ("*", "Old/New"): "旧 / 新",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:649
    ("*", "Tartiary Detail"): "详细性",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:689
    ("*", "Plastic Gloss"): "塑胶 光泽",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:717
    ("*", "Plastic Bump"): "塑胶 凹凸",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:749
    ("*", "Plastic Matte"): "塑胶 哑光",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:777
    ("*", "Plastic Emission"): "塑胶 发射",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:806
    ("*", "Liquid Water"): "液体 水",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:833
    ("*", "Liquid Cloudy"): "液体 多云",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:870
    ("*", "Artistic Watercolor"): "艺术性的 水彩画",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:875
    ("*", "Background Scale"): "背景缩放",
    #: mmd_uuunyaa_tools/tuners/material_tuners.py:876
    ("*", "Bleed Strength"): "渗水强度",
    #: mmd_uuunyaa_tools/tuners/operators.py:13
    ("Operator", "Tune Lighting"): "照明调整",
    #: mmd_uuunyaa_tools/tuners/operators.py:31
    ("Operator", "Freeze Lighting"): "照明冻结",
    #: mmd_uuunyaa_tools/tuners/operators.py:48
    ("Operator", "Tune Material"): "材质调整",
    #: mmd_uuunyaa_tools/tuners/operators.py:66
    ("Operator", "Attach Material Adjuster"): "附上材质调整器",
    #: mmd_uuunyaa_tools/tuners/operators.py:82
    ("Operator", "Detach Material Adjuster"): "分离材质调整器",
    #: mmd_uuunyaa_tools/tuners/operators.py:102
    ("Operator", "Tune Geometry Nodes"): "几何节点调整",
    #: mmd_uuunyaa_tools/tuners/panels.py:20
    ("*", "MMD UuuNyaa Sky"): "MMD UuuNyaa天空",
    #: mmd_uuunyaa_tools/tuners/panels.py:30
    ("*", "Light Strength"): "光照强度",
    #: mmd_uuunyaa_tools/tuners/panels.py:31
    ("*", "Image Strength"): "表示强度",
    #: mmd_uuunyaa_tools/tuners/panels.py:43
    ("*", "UuuNyaa World not found."): "没有找到UuuNyaa世界环境",
    #: mmd_uuunyaa_tools/tuners/panels.py:48
    ("*", "IrradianceVolume not found. Please add it."): "没有找到辐射体积。请添加它。",
    #: mmd_uuunyaa_tools/tuners/panels.py:53
    ("*", "for Eevee lighting, check Render Properties."): "对于Eevee照明，请检查渲染属性。",
    #: mmd_uuunyaa_tools/tuners/panels.py:58
    ("*", "Bake Indirect Lighting"): "烘焙间接光照明",
    #: mmd_uuunyaa_tools/tuners/panels.py:76
    ("*", "MMD UuuNyaa Lighting"): "MMD UuuNyaa照明",
    #: mmd_uuunyaa_tools/tuners/panels.py:115
    ("*", "MMD UuuNyaa Material"): "MMD UuuNyaa材质",
    #: mmd_uuunyaa_tools/tuners/panels.py:151
    ("*", "MMD UuuNyaa Material Adjuster"): "MMD UuuNyaa材质调整器",
    #: mmd_uuunyaa_tools/tuners/panels.py:168
    ("*", "{material_name} is unsupported. Select other material to be output from Principled BSDF."): "{material_name}是不支持的。选择要从原理化BSDF输出的其他材质。",
    #: mmd_uuunyaa_tools/tuners/panels.py:199
    ("*", "MMD UuuNyaa Geometry Nodes"): "MMD UuuNyaa几何节点调整器",
    #: mmd_uuunyaa_tools/tuners/properties.py:17
    ("*", "Choose the lighting you want to use"): "选择你的照明",
    #: mmd_uuunyaa_tools/tuners/properties.py:38
    ("*", "Choose the material you want to use"): "选择你的材质",
    #: mmd_uuunyaa_tools/tuners/properties.py:63
    ("*", "Choose the geometry nodes you want to use"): "选择你的几何节点",
  },
}
# ##### END AUTOGENERATED I18N SECTION #####
